CLI.cpp
Time CurrentLocalTime
NavigationDataType NavData
TinyGPSPlus gps
char Version[][]
char VersionDate[][]
configValuesType Configuration
MissionValuesStruct MissionValues
StateValuesStruct StateValues
bool UseSimulatedGPS
Referenced by CLI_Processor.
IMUStruct myIMU
HardwareSerial* Serials[][]
Referenced by CLI_Process_Message, CLI_Processor, ListParameter, ShowCommandState.
char MessageDisplayLine1[10][10]
Referenced by CLI_Processor.
char MessageDisplayLine2[10][10]
Referenced by CLI_Processor.
double PowerSensorV
double PowerSensorI
MPU9250 WingSailAngleSensor
BTStateType BTState
Referenced by CLI_Processor.
bool SD_Card_Present
WingSailType WingSail
double SteeringServoOutput
char CLI_Msg[50][50]
Referenced by CLI_Process_Message, CLI_Processor.
int CLI_i
Referenced by CLI_Process_Message, CLI_Processor.
void CLI_Process_Message(int CommandPort)
References CLI_i, CLI_Msg, CLI_Processor, CommandPort, Serials.
void CLI_Processor(int CommandPort, String Command)
References CLI_i, CLI_Msg, CLI_Processor.
Referenced by CLI_Process_Message, CLI_Processor, Load_ConfigValues.
void CLI_Processor(int CommandPort)
References configValuesType::BluetoothPort, MissionCommand::boundary, configValuesType::BTPortBaudRate, BTState, CCG, CCS, CLI_Msg, MissionCommand::cmd, CommandPort, configValuesType::CommandPort, configValuesType::CommandPortBaudRate, StateValuesStruct::CommandState, configValuesType::CompassOffsetAngle, Connected, MissionCommand::controlMask, ctGotoWaypoint, ctLoiter, ctLoiterUntil, ctReturnToHome, ctSteerWindCourse, NavigationDataType::Currentloc, configValuesType::DisplayScreenView, configValuesType::DualRudder, MissionCommand::duration, EQG, configValuesType::FailsafeCommandState, GetBTStatus, HLG, HLS, StateValuesStruct::home, StateValuesStruct::home_is_set, IMU_Mag_Init, IMU_Save_Cal, LAT, Location::lat, LCD, ListParameter, LMI, LNA, Location::lng, location_update, LOG, configValuesType::LoiterRadius, LPO, LSV, LVS, LWI, LWP, MPU9250::MagneticAngleCalibrationMode, configValuesType::MagnetVariation, configValuesType::MaxFileSize, configValuesType::MaximumTimePastFavouredTack, MCC, MCP, MessageDisplayLine1, MessageDisplayLine2, MIG, configValuesType::MinimumAngleDownWind, configValuesType::MinimumAngleUpWind, configValuesType::MinimumWindChangeTime, MIS, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, MissionValuesStruct::MissionList, configValuesType::mx_max, configValuesType::mx_min, configValuesType::my_max, configValuesType::my_min, NavigationDataType::next_WP_valid, configValuesType::pidCentre, configValuesType::pidDirection, configValuesType::pidKd, configValuesType::pidKi, configValuesType::pidKp, configValuesType::pidOutputmax, configValuesType::pidOutputmin, PRL, QueueMessage, configValuesType::RC_FailSafe_Ch0, configValuesType::RC_FailSafe_Ch1, configValuesType::RC_FailSafe_Ch2, configValuesType::RC_FailSafe_Ch3, configValuesType::RC_FailSafe_Time, configValuesType::RC_IN_Channel_Command, configValuesType::RC_IN_Channel_Motor, configValuesType::RC_IN_Channel_Sail, configValuesType::RC_IN_Channel_Steering, configValuesType::RC_IN_Command_Threhold0, configValuesType::RC_IN_Command_Threhold1, configValuesType::RC_IN_Command_Threhold2, configValuesType::RC_IN_Command_Threhold3, configValuesType::RC_IN_Command_Threhold4, configValuesType::RC_IN_Command_Threhold9, RCPowerOn, configValuesType::SailableAngleMargin, configValuesType::SatCommsPort, configValuesType::SatCommsPortBaudRate, Save_EEPROM_ConfigValues, Save_EEPROM_Mission, Save_EEPROM_StateValues, configValuesType::SaveStateValues, SCG, SCS, SD_Logging_Event_ParameterChange, configValuesType::SDCardLogDelimiter, configValuesType::SDCardLoggingMask, Serials, configValuesType::Servo_Channel_Motor, configValuesType::Servo_Channel_Sail, configValuesType::Servo_Channel_Steering, configValuesType::Servo_Channel_Steering_Stbd, set_next_WP_for_display, StateValuesStruct::StartingMission, MissionCommand::SteerAWA, StateValuesStruct::SteerCompassBearing, SteeringPID_Init, StateValuesStruct::SteerWindAngle, configValuesType::TargetHeadingFilterConstant, configValuesType::TelemetryLoggingMask, TelemetryPowerOn, configValuesType::timezone_offset, TMG, MissionCommand::TrimTabAngle, configValuesType::TrimTabDefaultAngle, configValuesType::TrimTabOffset, configValuesType::TrimTabScale, configValuesType::TWD_Offset, configValuesType::UseMotor, UseSimulatedGPS, VER, MissionCommand::waypoint, WC0, WC1, configValuesType::WindAngleCalibrationOffset, configValuesType::WPCourseHoldRadius.
void ListParameter(int CommandPort, int ParameterIndex)
References configValuesType::BluetoothPort, configValuesType::BTPortBaudRate, CommandPort, configValuesType::CommandPort, configValuesType::CommandPortBaudRate, CommandStateToString, configValuesType::CompassOffsetAngle, configValuesType::DisplayScreenView, configValuesType::DualRudder, configValuesType::FailsafeCommandState, configValuesType::LoiterRadius, configValuesType::MagnetVariation, configValuesType::MaxFileSize, configValuesType::MaximumTimePastFavouredTack, configValuesType::MinimumAngleDownWind, configValuesType::MinimumAngleUpWind, configValuesType::MinimumWindChangeTime, configValuesType::mx_max, configValuesType::mx_min, configValuesType::my_max, configValuesType::my_min, configValuesType::pidCentre, configValuesType::pidDirection, configValuesType::pidKd, configValuesType::pidKi, configValuesType::pidKp, configValuesType::pidOutputmax, configValuesType::pidOutputmin, configValuesType::RC_FailSafe_Ch0, configValuesType::RC_FailSafe_Ch1, configValuesType::RC_FailSafe_Ch2, configValuesType::RC_FailSafe_Ch3, configValuesType::RC_FailSafe_Time, configValuesType::RC_IN_Channel_Command, configValuesType::RC_IN_Channel_Motor, configValuesType::RC_IN_Channel_Sail, configValuesType::RC_IN_Channel_Steering, configValuesType::RC_IN_Command_Threhold0, configValuesType::RC_IN_Command_Threhold1, configValuesType::RC_IN_Command_Threhold2, configValuesType::RC_IN_Command_Threhold3, configValuesType::RC_IN_Command_Threhold4, configValuesType::RC_IN_Command_Threhold9, configValuesType::SailableAngleMargin, configValuesType::SatCommsPort, configValuesType::SatCommsPortBaudRate, configValuesType::SaveStateValues, configValuesType::SDCardLogDelimiter, configValuesType::SDCardLoggingMask, Serials, configValuesType::Servo_Channel_Motor, configValuesType::Servo_Channel_Sail, configValuesType::Servo_Channel_Steering, configValuesType::Servo_Channel_Steering_Stbd, configValuesType::TargetHeadingFilterConstant, configValuesType::TelemetryLoggingMask, configValuesType::timezone_offset, configValuesType::TrimTabDefaultAngle, configValuesType::TrimTabOffset, configValuesType::TrimTabScale, configValuesType::TWD_Offset, configValuesType::UseMotor, configValuesType::WindAngleCalibrationOffset, configValuesType::WPCourseHoldRadius.
Referenced by CLI_Processor, SendMessage.
void ShowCommandState(int CommandPort, VesselCommandStateType cs)
References CommandPort, Serials, vcsFollowMission, vcsFullManual, vcsIdle, vcsLoiter, vcsPartialManual, vcsResetMissionIndex, vcsReturnToHome, vcsSetHome, vcsSteerMagneticCourse, vcsSteerWindCourse.
Referenced by SendMessage.