GPS.h
void GPS_Init(int CommandPort)
References I2CGPS::begin, CommandPort, GPS_Read, GPS_Read_Time, Serials, configValuesType::timezone_offset, UpdateLocalTimeFromGPSTime.
void GPS_Read(void)
References I2CGPS::available, NavigationDataType::COG, TinyGPSPlus::course, NavigationDataType::Currentloc, NavigationDataType::CurrentLocTimeStamp, TinyGPSPlus::date, TinyGPSDate::day, Time::dayOfMonth, TinyGPSCourse::deg, TinyGPSPlus::encode, GPS_Last_Loc, GPS_Last_Message, Time::hour, TinyGPSTime::hour, TinyGPSSpeed::knots, Location::lat, TinyGPSLocation::lat, Location::lng, TinyGPSLocation::lng, TinyGPSPlus::location, Time::minute, TinyGPSTime::minute, Time::month, TinyGPSDate::month, TinyGPSSpeed::mps, I2CGPS::read, Time::second, TinyGPSTime::second, NavigationDataType::SOG_knt, NavigationDataType::SOG_mps, TinyGPSPlus::speed, TinyGPSPlus::time, Time::year, TinyGPSDate::year.
Referenced by GPS_Init.
bool GPS_LocationIs_Valid(Location TestLoc)
References GPS_Last_Loc, Location::lat, Location::lng, UseSimulatedGPS.
Referenced by MissionUpdate, NavigationUpdate_SlowData, OLED_Logging, SD_Logging, SteeringFastUpdate, wingsail_update.
bool GPS_TimeIs_Valid()
References Time::month.
Referenced by Check_GPS_TimeStatus.
void GPS_Read_Time(void)
References I2CGPS::available, TinyGPSPlus::date, TinyGPSDate::day, Time::dayOfMonth, TinyGPSPlus::encode, Time::hour, TinyGPSTime::hour, Time::minute, TinyGPSTime::minute, Time::month, TinyGPSDate::month, I2CGPS::read, Time::second, TinyGPSTime::second, TinyGPSPlus::time, Time::year, TinyGPSDate::year.
Referenced by GPS_Init.
void UpdateLocalTimeFromGPSTime(byte timezone_offset)
References Time::dayOfMonth, DaysInMonth, Time::hour, Time::minute, Time::month, Time::second, Time::year.
Referenced by GPS_Init.
byte DaysInMonth(byte month, byte year)
Referenced by UpdateLocalTimeFromGPSTime.