RadioControl.cpp
RC_Ch0_IN_PIN
Referenced by isrCh0_IN, RC_Init.
RC_Ch1_IN_PIN
Referenced by isrCh1_IN, RC_Init.
RC_Ch2_IN_PIN
Referenced by isrCh2_IN, RC_Init.
RC_Ch3_IN_PIN
Referenced by isrCh3_IN, RC_Init.
Servo_Ch0_OUT_PIN
Referenced by Servos_Init.
Servo_Ch1_OUT_PIN
Referenced by Servos_Init.
Servo_Ch2_OUT_PIN
Referenced by Servos_Init.
Servo_Ch3_OUT_PIN
Referenced by Servos_Init.
RC_Ch0_IN_FLAG
Referenced by isrCh0_IN.
RC_Ch1_IN_FLAG
Referenced by isrCh1_IN.
RC_Ch2_IN_FLAG
Referenced by isrCh2_IN.
RC_Ch3_IN_FLAG
Referenced by isrCh3_IN.
RC_PulseWidth_Min
Referenced by Servo_Out.
RC_PulseWidth_Max
Referenced by Servo_Out.
RC_IN_Type RC_IN
configValuesType Configuration
Servo Servo_Channel[4][4]
Referenced by Servo_Out, Servos_Init.
volatile uint16_t RC_Ch0InShared
Referenced by isrCh0_IN, RC_Read.
volatile uint16_t RC_Ch1InShared
Referenced by isrCh1_IN, RC_Read.
volatile uint16_t RC_Ch2InShared
Referenced by isrCh2_IN, RC_Read.
volatile uint16_t RC_Ch3InShared
Referenced by isrCh3_IN, RC_Read.
volatile uint8_t bUpdateFlagsShared
Referenced by isrCh0_IN, isrCh1_IN, isrCh2_IN, isrCh3_IN, RC_Read.
uint32_t RC_Ch0_IN_Start
Referenced by isrCh0_IN.
uint32_t RC_Ch1_IN_Start
Referenced by isrCh1_IN.
uint32_t RC_Ch2_IN_Start
Referenced by isrCh2_IN.
uint32_t RC_Ch3_IN_Start
Referenced by isrCh3_IN.
void isrCh0_IN()
References bUpdateFlagsShared, RC_Ch0_IN_FLAG, RC_Ch0_IN_PIN, RC_Ch0_IN_Start, RC_Ch0InShared.
Referenced by RC_Init.
void isrCh1_IN()
References bUpdateFlagsShared, RC_Ch1_IN_FLAG, RC_Ch1_IN_PIN, RC_Ch1_IN_Start, RC_Ch1InShared.
Referenced by RC_Init.
void isrCh2_IN()
References bUpdateFlagsShared, RC_Ch2_IN_FLAG, RC_Ch2_IN_PIN, RC_Ch2_IN_Start, RC_Ch2InShared.
Referenced by RC_Init.
void isrCh3_IN()
References bUpdateFlagsShared, RC_Ch3_IN_FLAG, RC_Ch3_IN_PIN, RC_Ch3_IN_Start, RC_Ch3InShared.
Referenced by RC_Init.
void RC_Init(void)
References isrCh0_IN, isrCh1_IN, isrCh2_IN, isrCh3_IN, RC_Ch0_IN_PIN, RC_Ch1_IN_PIN, RC_Ch2_IN_PIN, RC_Ch3_IN_PIN.
void Servos_Init(void)
References configValuesType::RC_FailSafe_Ch0, configValuesType::RC_FailSafe_Ch1, configValuesType::RC_FailSafe_Ch2, configValuesType::RC_FailSafe_Ch3, Servo_Ch0_OUT_PIN, Servo_Ch1_OUT_PIN, Servo_Ch2_OUT_PIN, Servo_Ch3_OUT_PIN, Servo_Channel.
void RC_Read(void)
References bUpdateFlagsShared, RC_IN_Type::Channel, RC_IN_Type::LastRCSignalTime, RC_Ch0InShared, RC_Ch1InShared, RC_Ch2InShared, RC_Ch3InShared, RC_Command_Switch, configValuesType::RC_FailSafe_Ch0, configValuesType::RC_FailSafe_Ch1, configValuesType::RC_FailSafe_Ch2, configValuesType::RC_FailSafe_Ch3, configValuesType::RC_FailSafe_Time, RC_IN_Type::SignalValid.
void RC_Command_Switch(void)
References RC_IN_Type::Channel, RC_IN_Type::RC_Command_Switch_Position, configValuesType::RC_IN_Command_Threhold1, configValuesType::RC_IN_Command_Threhold2, configValuesType::RC_IN_Command_Threhold3, configValuesType::RC_IN_Command_Threhold4, RC_IN_Type::SignalValid.
Referenced by RC_Read.
void Servo_Out(int Channel, int PulseWidth)
References RC_PulseWidth_Max, RC_PulseWidth_Min, Servo_Channel.
Referenced by SteeringFastUpdate.