SailingNavigation.cpp
NavigationDataType NavData
StateValuesStruct StateValues
configValuesType Configuration
MissionValuesStruct MissionValues
DecisionEventType DecisionEvent
Referenced by LimitToSailingCourse, SetTack, SteerCloseHauled, SteerDeepRunning, UpdateCourseToSteer.
DecisionEventReasonType DecisionEventReason
Referenced by LimitToSailingCourse, SetTack, UpdateCourseToSteer.
int CommandPort
Referenced by LimitToSailingCourse, SetTack, UpdateCourseToSteer.
LowPassAngleFilter TargetHeadingFilter
void SailingNavigation_Init(void)
References LowPassAngleFilter::FilterConstant, configValuesType::TargetHeadingFilterConstant.
void UpdateCourseToSteer(void)
References NavigationDataType::AWA, CalculateSailingCTS, MissionCommand::cmd, CommandPort, StateValuesStruct::CommandState, ctGotoWaypoint, ctLoiter, ctLoiterUntil, ctReturnToHome, NavigationDataType::CTS, ctSteerWindCourse, DecisionEvent, DecisionEventReason, deHoldCourse, NavigationDataType::DTW, NavigationDataType::HDG, LimitToSailingCourse, LoiterCalcCTS, StateValuesStruct::mission_index, MissionValuesStruct::MissionList, rApproachingWP, SD_Logging_Event_Decisions, configValuesType::SDCardLoggingMask, StateValuesStruct::SteerCompassBearing, StateValuesStruct::SteerWindAngle, TelemetryLogging_Event_Decisions, configValuesType::TelemetryLoggingMask, vcsFollowMission, vcsFullManual, vcsLoiter, vcsPartialManual, vcsResetMissionIndex, vcsReturnToHome, vcsSetHome, vcsSteerMagneticCourse, vcsSteerWindCourse, configValuesType::WPCourseHoldRadius, wrap_360.
int CalculateSailingCTS(void)
References NavigationDataType::BTW, NavigationDataType::CourseType, ctDirectToWayPoint, NavigationDataType::CTE, NavigationDataType::CTE_Correction, ctPortTack, ctStarboardTack, NavigationDataType::FavouredTack, NavigationDataType::IsBTWSailable, NavigationDataType::Manoeuvre, NavigationDataType::ManoeuvreState, NavigationDataType::MaxCTE, mstCommence, mtGybe, rFavouredTack, rNoChange, rPastBoundary, SetTack, NavigationDataType::TackDuration, wrap_360.
Referenced by UpdateCourseToSteer.
int SetTack(SteeringCourseType Tack, DecisionEventReasonType Reason)
References NavigationDataType::BTW, CommandPort, NavigationDataType::CourseType, ctDirectToWayPoint, ctPortTack, ctPortTackRunning, ctStarboardTack, ctStarboardTackRunning, DecisionEvent, DecisionEventReason, deTackToPort, deTackToPortRunning, deTackToStarboard, deTackToStarboardRunning, rNoChange, SD_Logging_Event_Decisions, configValuesType::SDCardLoggingMask, SteerCloseHauled, SteerDeepRunning, TelemetryLogging_Event_Decisions, configValuesType::TelemetryLoggingMask.
Referenced by CalculateSailingCTS.
void UpdateTargetHeading(void)
References LowPassAngleFilter::Filter, NavigationDataType::TargetHDG, NavigationDataType::TurnHDG.
SteeringCourseType GetFavouredTack(NavigationDataType NavData)
References NavigationDataType::BTW, ctPortTack, ctStarboardTack, NavigationDataType::TWD, wrap_180.
Referenced by NavigationUpdate_SlowData.
int LimitToSailingCourse(int Course)
References NavigationDataType::AWA, AWA_Calculated, CommandPort, NavigationDataType::CourseType, ctPortTack, ctPortTackRunning, ctStarboardTack, ctStarboardTackRunning, DecisionEvent, DecisionEventReason, deTackToPort, deTackToPortRunning, deTackToStarboard, deTackToStarboardRunning, configValuesType::MinimumAngleDownWind, configValuesType::MinimumAngleUpWind, NavigationDataType::PortLayline, NavigationDataType::PortLaylineRunning, rLimitToSailingCourse, SD_Logging_Event_Decisions, configValuesType::SDCardLoggingMask, NavigationDataType::StarboardLayline, NavigationDataType::StarboardLaylineRunning, TelemetryLogging_Event_Decisions, configValuesType::TelemetryLoggingMask, NavigationDataType::TWD, wrap_180.
Referenced by LoiterCalcCTS, UpdateCourseToSteer.
int SteerCloseHauled(SteeringCourseType Tack)
References NavigationDataType::AWA, NavigationDataType::BTW, ctDirectToWayPoint, ctPortTack, ctStarboardTack, DecisionEvent, deTackToPort, deTackToStarboard, NavigationDataType::HDG, configValuesType::MinimumAngleUpWind, wrap_360.
Referenced by SetTack.
int SteerDeepRunning(SteeringCourseType Tack)
References NavigationDataType::AWA, NavigationDataType::BTW, ctDirectToWayPoint, ctPortTack, ctStarboardTack, DecisionEvent, deTackToPort, deTackToStarboard, NavigationDataType::HDG, configValuesType::MinimumAngleDownWind, wrap_360.
Referenced by SetTack.
SteeringCourseType GetPointOfSail(int WindAngle)
References ctNotEstablished, ctPortTack, ctPortTackRunning, ctStarboardTack, ctStarboardTackRunning, WindAngle.
Referenced by NavigationUpdate_SlowData.
bool IsBTWSailable(NavigationDataType NavData)
References NavigationDataType::CTE, NavigationDataType::MaxCTE, configValuesType::MinimumAngleDownWind, configValuesType::MinimumAngleUpWind, configValuesType::SailableAngleMargin, NavigationDataType::WindAngleToWaypoint.
Referenced by NavigationUpdate_SlowData.