TelemetryLogging.h
DecisionEventType
DecisionEventReasonType
const int Log_Location
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Attitude
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Situation
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Waypoints
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Sailing
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Navigation
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_System
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_GPS
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Decisions
Referenced by SD_Logging_Event_Decisions, SD_Logging_OpenFile, TelemetryLogging_Event_Decisions.
const int Log_ServoOut
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Voltages
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Usage
Referenced by SD_Logging_Event_Usage, SD_Logging_OpenFile.
const int Log_Environment
Referenced by SD_Logging, SD_Logging_OpenFile.
const int Log_Messages
void TelemetryLogging_Event_Decisions(int CommandPort, word LoggingMask)
References CommandPort, StateValuesStruct::CommandState, CommandStateToString, DecisionEvent, DecisionEventReason, DecisionEventReasonToString, DecisionEventToString, Log_Decisions, StateValuesStruct::mission_index, Serials, TelemetryLogTime.
Referenced by CommandState_Processor, IsMissionStepComplete, LimitToSailingCourse, LoiterCalcCTS, SetTack, UpdateCourseToSteer.
String CommandStateToString(VesselCommandStateType CommandState)
References vcsFollowMission, vcsFullManual, vcsIdle, vcsLoiter, vcsPartialManual, vcsResetMissionIndex, vcsReturnToHome, vcsSetHome, vcsSteerMagneticCourse, vcsSteerWindCourse.
Referenced by ListParameter, SD_Logging_Event_Decisions, SendMessage, TelemetryLogging_Event_Decisions.
String DecisionEventToString(DecisionEventType DecisionEvent)
References deChangeCommandState, deEndOfMission, deHoldCourse, deIncrementMissionIndex, dePastWaypoint, deTackToPort, deTackToPortRunning, deTackToStarboard, deTackToStarboardRunning.
Referenced by SD_Logging_Event_Decisions, TelemetryLogging_Event_Decisions.
String DecisionEventReasonToString(DecisionEventReasonType DecisionEventReason)
References rApproachingWP, rFavouredTack, rLimitToSailingCourse, rManualIntervention, rNoChange, rNone, rPastBoundary, rPastDuration, rPastLoiterBoundary, rPastTime, rPastWaypoint, rUnkown.
Referenced by SD_Logging_Event_Decisions, TelemetryLogging_Event_Decisions.
String CourseTypeToString(SteeringCourseType CourseType)
References ctDirectToWayPoint, ctPortTack, ctStarboardTack.
Referenced by OLED_Logging, SD_Logging.
String CourseTypeToString(ManoeuvreStateType ManoeuvreState)
References mstCommence, mstComplete, mstNone, mstRunning.