imu::Vector
double imu::Vector< N >::p_vec[N][N]
Referenced by imu::Vector< N >::cross, imu::Vector< N >::dot, imu::Vector< N >::invert, imu::Vector< N >::magnitude, imu::Vector< N >::normalize, imu::Vector< N >::operator(), imu::Vector< N >::operator+, imu::Vector< N >::operator-, imu::Vector< N >::operator/, imu::Vector< N >::operator=, imu::Vector< N >::operator[], imu::Vector< N >::scale, imu::Vector< N >::toDegrees, imu::Vector< N >::toRadians, imu::Vector< N >::Vector, imu::Vector< N >::x, imu::Vector< N >::y, imu::Vector< N >::z.
imu::Vector< N >::Vector()
References imu::Vector< N >::p_vec.
imu::Vector< N >::Vector(double a)
References imu::Vector< N >::p_vec.
imu::Vector< N >::Vector(double a, double b)
References imu::Vector< N >::p_vec.
imu::Vector< N >::Vector(double a, double b, double c)
References imu::Vector< N >::p_vec.
imu::Vector< N >::Vector(double a, double b, double c, double d)
References imu::Vector< N >::p_vec.
imu::Vector< N >::Vector(const Vector< N > &v)
References imu::Vector< N >::p_vec, imu::Vector< N >::x.
imu::Vector< N >::~Vector()
uint8_t imu::Vector< N >::n()
Referenced by imu::Vector< N >::operator(), imu::Vector< N >::operator[].
double imu::Vector< N >::magnitude() const
References imu::Vector< N >::p_vec.
Referenced by imu::Vector< N >::normalize.
void imu::Vector< N >::normalize()
References imu::Vector< N >::magnitude, imu::Vector< N >::p_vec.
double imu::Vector< N >::dot(const Vector &v) const
References imu::Vector< N >::p_vec.
Vector imu::Vector< N >::cross(const Vector &v) const
Vector imu::Vector< N >::scale(double scalar) const
References imu::Vector< N >::p_vec.
Referenced by imu::Vector< N >::operator*.
Vector imu::Vector< N >::invert() const
References imu::Vector< N >::p_vec.
Vector& imu::Vector< N >::operator=(const Vector &v)
References imu::Vector< N >::p_vec, imu::Vector< N >::x.
double& imu::Vector< N >::operator[](int n)
References imu::Vector< N >::n, imu::Vector< N >::p_vec.
double imu::Vector< N >::operator[](int n) const
References imu::Vector< N >::n, imu::Vector< N >::p_vec.
double& imu::Vector< N >::operator()(int n)
References imu::Vector< N >::n, imu::Vector< N >::p_vec.
double imu::Vector< N >::operator()(int n) const
References imu::Vector< N >::n, imu::Vector< N >::p_vec.
Vector imu::Vector< N >::operator+(const Vector &v) const
References imu::Vector< N >::p_vec.
Vector imu::Vector< N >::operator-(const Vector &v) const
References imu::Vector< N >::p_vec.
Vector imu::Vector< N >::operator*(double scalar) const
References imu::Vector< N >::scale.
Vector imu::Vector< N >::operator/(double scalar) const
References imu::Vector< N >::p_vec.
void imu::Vector< N >::toDegrees()
References imu::Vector< N >::p_vec.
void imu::Vector< N >::toRadians()
References imu::Vector< N >::p_vec.
double& imu::Vector< N >::x()
References imu::Vector< N >::p_vec.
Referenced by imu::Vector< N >::operator=, imu::Vector< N >::Vector.
double& imu::Vector< N >::y()
References imu::Vector< N >::p_vec.
double& imu::Vector< N >::z()
References imu::Vector< N >::p_vec.
double imu::Vector< N >::x() const
References imu::Vector< N >::p_vec.
double imu::Vector< N >::y() const
References imu::Vector< N >::p_vec.
double imu::Vector< N >::z() const
References imu::Vector< N >::p_vec.
Vector< 3 > imu::Vector< 3 >::cross(const Vector &v) const
References imu::Vector< N >::p_vec.