Navigation.cpp
IMUStruct myIMU
NavigationDataType NavData
configValuesType Configuration
WingSailType WingSail
MPU9250 WingSailAngleSensor
LowPassAngleFilter TrueWindFilter
LowPassFilter RollFilter
LowPassFilter HeadingErrorFilter
LowPassFilter SOGFilter
LowPassAngleFilter COGFilter
void NavigationUpdate_SlowData(void)
References NavigationDataType::AWA, NavigationDataType::BTW, NavigationDataType::CDA, NavigationDataType::COG_Avg, NavigationDataType::CourseType, NavigationDataType::CTE, NavigationDataType::CTE_Correction, NavigationDataType::Currentloc, NavigationDataType::DTW, NavigationDataType::FavouredTack, get_bearing, get_CTE, get_CTE_Correction, get_distance, GetFavouredTack, GetPointOfSail, GPS_LocationIs_Valid, NavigationDataType::IsBTWSailable, IsBTWSailable, NavigationDataType::MaxCTE, configValuesType::MinimumAngleDownWind, configValuesType::MinimumAngleUpWind, NavigationDataType::next_WP, NavigationDataType::next_WP_valid, NavigationDataType::PastWP, NavigationDataType::PortLayline, NavigationDataType::PortLaylineRunning, NavigationDataType::prev_WP, reached_waypoint_point, NavigationDataType::RLB, NavigationDataType::SOG_Avg, NavigationDataType::StarboardLayline, NavigationDataType::StarboardLaylineRunning, NavigationDataType::TWD, NavigationDataType::VMC, NavigationDataType::VMG, NavigationDataType::WindAngleToWaypoint, wrap_180, wrap_360.
void NavigationUpdate_MediumData(void)
References NavigationDataType::COG, NavigationDataType::COG_Avg, LowPassFilter::Filter, IMUStruct::roll, NavigationDataType::ROLL_Avg, NavigationDataType::SOG_Avg, NavigationDataType::SOG_mps.
void NavigationUpdate_FastData(void)
References NavigationDataType::COG, configValuesType::CompassOffsetAngle, LowPassFilter::Filter, NavigationDataType::HDG, NavigationDataType::HDG_Err, NavigationDataType::HDG_Mag, IMUStruct::heading, configValuesType::MagnetVariation, NavigationDataType::SOG_mps, wrap_180, wrap_360.
void GetApparentWind(void)
References NavigationDataType::AWA, MPU9250::MagneticAngle, WingSailType::TrimTabAngle.
void Navigation_Init(void)
References LowPassFilter::FilterConstant, LowPassAngleFilter::FilterConstant.
void GetTrueWind(void)
References NavigationDataType::AWA, NavigationDataType::AWD, LowPassAngleFilter::Filter, NavigationDataType::HDG, NavigationDataType::TWD, configValuesType::TWD_Offset, wrap_360.
void UpdateTurnHeadingV2(void)
References NavigationDataType::AWA, AWA_Calculated, NavigationDataType::AWD, NavigationDataType::CTS, NavigationDataType::ManoeuvreState, mstCommence, mstComplete, mstNone, mstRunning, mtGybe, configValuesType::TackingMethod, NavigationDataType::TurnHDG, NavigationDataType::TWD, wrap_180, wrap_360.
int get_CTE_Correction(NavigationDataType NavData)
References NavigationDataType::CTE, configValuesType::CTE_CorrectionGain, NavigationDataType::MaxCTE.
Referenced by NavigationUpdate_SlowData.
int AWA_Calculated(int CTS, int TWD)
References wrap_180.
Referenced by LimitToSailingCourse, UpdateTurnHeadingV2.