OLED_Logging.cpp
OLED_RESET
NavigationDataType NavData
StateValuesStruct StateValues
IMUStruct myIMU
char Version[][]
Referenced by OLED_Logging.
char VersionDate[][]
Referenced by OLED_Logging.
Time CurrentLocalTime
RC_IN_Type RC_IN
HardwareSerial* Serials[][]
Referenced by OLED_Init.
bool SD_Card_Present
Referenced by OLED_Logging.
configValuesType Configuration
int CommandPort
Referenced by OLED_Logging.
uint32_t CommandPortBaudRate
Referenced by OLED_Logging.
MissionValuesStruct MissionValues
char MessageDisplayLine1[10][10]
Referenced by OLED_Logging.
char MessageDisplayLine2[10][10]
Referenced by OLED_Logging.
LoiterStruct LoiterData
double PowerSensorV
Referenced by OLED_Logging.
double PowerSensorI
Referenced by OLED_Logging.
byte BluetoothStatePin
Referenced by OLED_Logging.
BTStateType BTState
Referenced by OLED_Logging.
MPU9250 WingSailAngleSensor
WingSailType WingSail
VesselUsageCountersStruct VesselUsageCounters
byte OLED_PowerPin
Adafruit_SSD1306 display(OLED_RESET)(OLED_RESET)
Referenced by OLED_Init, OLED_Logging.
const byte OLED_Address
Referenced by OLED_Init.
bool OLED_Present
Referenced by OLED_Init, OLED_Logging.
void OLED_Init(int SerialPortNumber)
References Adafruit_SSD1306::begin, Adafruit_SSD1306::clearDisplay, display, Adafruit_SSD1306::display, OLED_Address, OLED_Present, Serials, Adafruit_GFX::setTextColor, Adafruit_GFX::setTextSize, SSD1306_SWITCHCAPVCC, WHITE.
void OLED_Logging(char LoggingLevel)
References IMUStruct::Algorithm_Status, WingSailType::Angle, NavigationDataType::AWA, IMUStruct::baro_pressure, IMUStruct::baro_temperature, configValuesType::BluetoothPort, BluetoothStatePin, configValuesType::BTPortBaudRate, BTState, LoiterStruct::BTW, NavigationDataType::BTW, NavigationDataType::CDA, RC_IN_Type::Channel, Adafruit_SSD1306::clearDisplay, MissionCommand::cmd, NavigationDataType::COG, CommandPort, CommandPortBaudRate, StateValuesStruct::CommandState, configValuesType::CompassOffsetAngle, NavigationDataType::CourseType, CourseTypeToString, ctDirectToWayPoint, NavigationDataType::CTE, NavigationDataType::CTE_Correction, ctNotEstablished, ctPortTack, ctPortTackRunning, NavigationDataType::CTS, ctStarboardTack, ctStarboardTackRunning, NavigationDataType::Currentloc, Time::dayOfMonth, display, Adafruit_SSD1306::display, LoiterStruct::DTW, NavigationDataType::DTW, MissionCommand::duration, GetBTStatus, GetMissionCommandString, GPS_LocationIs_Valid, NavigationDataType::HDG, NavigationDataType::HDG_Err, NavigationDataType::HDG_Mag, IMUStruct::heading, StateValuesStruct::home, StateValuesStruct::home_is_set, Time::hour, MPU9250::Initialsed, VesselUsageCountersStruct::intervalCounter, NavigationDataType::IsBTWSailable, Location::lat, Location::lng, LoiterStruct::loiterCentreLocation, LoiterStruct::LoiterState, lsApproach, lsNotLoitering, lsPortSide, lsStarboardSide, MPU9250::MagneticAngle, NavigationDataType::Manoeuvre, NavigationDataType::ManoeuvreState, NavigationDataType::MaxCTE, MessageDisplayLine1, MessageDisplayLine2, Time::minute, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, MissionValuesStruct::MissionCommandStartTime, MissionValuesStruct::MissionList, Time::month, mtGybe, mtNotDefined, mtTack, MPU9250::mx, MPU9250::mx_max, MPU9250::mx_min, MPU9250::my, MPU9250::my_max, MPU9250::my_min, NavigationDataType::next_WP, OLED_Present, NavigationDataType::PastWP, IMUStruct::pitch, NavigationDataType::PortLayline, NavigationDataType::PortLaylineRunning, VesselUsageCountersStruct::PortRudderCounter, PowerSensorI, PowerSensorV, NavigationDataType::prev_WP, RC_IN_Type::RC_Command_Switch_Position, IMUStruct::roll, SD_Card_Present, Time::second, WingSailType::Servo_microseconds, Adafruit_GFX::setCursor, Adafruit_GFX::setTextSize, RC_IN_Type::SignalValid, NavigationDataType::SOG_mps, Adafruit_SSD1306::ssd1306_command, SSD1306_DISPLAYOFF, SSD1306_DISPLAYON, NavigationDataType::StarboardLayline, NavigationDataType::StarboardLaylineRunning, VesselUsageCountersStruct::StarboardRudderCounter, WingSailType::State, MissionCommand::SteerAWA, StateValuesStruct::SteerCompassBearing, StateValuesStruct::SteerWindAngle, WingSailType::Tack, NavigationDataType::TargetHDG, WingSailType::TrimTabAngle, MissionCommand::TrimTabAngle, VesselUsageCountersStruct::TrimTabCounter, NavigationDataType::TurnHDG, NavigationDataType::TWD, NavigationDataType::TWS, vcsFollowMission, vcsFullManual, vcsIdle, vcsLoiter, vcsPartialManual, vcsResetMissionIndex, vcsReturnToHome, vcsSetHome, vcsSteerMagneticCourse, vcsSteerWindCourse, Version, VersionDate, NavigationDataType::WindAngleToWaypoint, wrap_360, wsForward, wsHeadToWind, wsIdle, wsPortTack, wsReverse, wsStarboardTack, Time::year.
Referenced by Local_Display_Logging.
String GetMissionCommandString(MissionCommandType cmd)
References ctGotoWaypoint, ctLoiter, ctLoiterUntil, ctReturnToHome, ctSteerWindCourse.
Referenced by OLED_Logging, SD_Logging_Event_MissionStep.