TelemetryMessages.cpp
HardwareSerial* Serials[][]
Referenced by SendMessage, SendMissionStep.
NavigationDataType NavData
IMUStruct myIMU
byte MessageArray[EndMarker][EndMarker]
Referenced by ProcessQueue, QueueMessage, SendMessage.
double PowerSensorV
Referenced by SendMessage.
double PowerSensorI
Referenced by SendMessage.
StateValuesStruct StateValues
WingSailType WingSail
double SteeringServoOutput
Referenced by SendMessage.
MissionValuesStruct MissionValues
char Version[][]
Referenced by SendMessage.
char VersionDate[][]
Referenced by SendMessage.
Time CurrentLocalTime
bool SD_Card_Present
Referenced by SendMessage.
configValuesType Configuration
MPU9250 WingSailAngleSensor
const int MaxParameterIndex
Referenced by QueueMessage, SendMessage.
void SendMessage(int CommandPort, TelMessageType msg)
References IMUStruct::Algorithm_Status, WingSailType::Angle, NavigationDataType::AWA, NavigationDataType::BTW, CCG, CCS, NavigationDataType::CDA, MissionCommand::cmd, NavigationDataType::COG, CommandPort, StateValuesStruct::CommandState, CommandStateToString, NavigationDataType::CTE, NavigationDataType::Currentloc, Time::dayOfMonth, configValuesType::DisplayScreenView, NavigationDataType::DTW, MissionCommand::duration, EQG, NavigationDataType::HDG, HLG, HLS, StateValuesStruct::home, StateValuesStruct::home_is_set, Time::hour, MPU9250::Initialsed, LAT, Location::lat, LCD, ListParameter, LMI, LNA, Location::lng, LOG, LPO, LSV, LVS, LWI, LWP, NavigationDataType::MaxCTE, MaxParameterIndex, MCC, MCP, MessageArray, MIG, Time::minute, MIS, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, MissionValuesStruct::MissionList, Time::month, NavigationDataType::next_WP, IMUStruct::pitch, PowerSensorI, PowerSensorV, NavigationDataType::prev_WP, PRL, IMUStruct::roll, NavigationDataType::ROLL_Avg, SCG, SCS, SD_Card_Present, configValuesType::SDCardLoggingMask, Time::second, SendMissionStep, Serials, WingSailType::Servo_microseconds, ShowCommandState, NavigationDataType::SOG_mps, MissionCommand::SteerAWA, StateValuesStruct::SteerCompassBearing, SteeringServoOutput, StateValuesStruct::SteerWindAngle, TMG, WingSailType::TrimTabAngle, MissionCommand::TrimTabAngle, NavigationDataType::TWD, NavigationDataType::TWS, vcsSteerMagneticCourse, vcsSteerWindCourse, VER, Version, VersionDate, NavigationDataType::VMG, WC0, WC1, Time::year.
Referenced by ProcessQueue.
void ProcessQueue(int SerialPortNumber)
References EndMarker, MessageArray, SendMessage.
void QueueMessage(TelMessageType msg)
References MaxParameterIndex, MCP, MessageArray, MissionValuesStruct::mission_size, PRL.
Referenced by CLI_Processor.
void SendMissionStep(int CommandPort, int i)
References MissionCommand::boundary, MissionCommand::cmd, CommandPort, MissionCommand::controlMask, ctGotoWaypoint, ctLoiter, ctLoiterUntil, ctReturnToHome, ctSteerWindCourse, MissionCommand::duration, Location::lat, Location::lng, MissionValuesStruct::MissionList, Serials, MissionCommand::SteerAWA, MissionCommand::TrimTabAngle, MissionCommand::waypoint.
Referenced by SendMessage.