TelemetryLogging.cpp
NavigationDataType NavData
StateValuesStruct StateValues
long loop_period_us
IMUStruct myIMU
long GPS_Last_Loc
Referenced by GPS_LocationIs_Valid, GPS_Read.
long GPS_Last_Message
Referenced by GPS_Read.
bool UseSimulatedGPS
Time CurrentLocalTime
int WindAngle
Referenced by GetPointOfSail.
HardwareSerial* Serials[][]
Referenced by TelemetryLogging_Event_Decisions, TelemetryLogTime.
DecisionEventType DecisionEvent
Referenced by TelemetryLogging_Event_Decisions.
DecisionEventReasonType DecisionEventReason
Referenced by TelemetryLogging_Event_Decisions.
VesselUsageCountersStruct VesselUsageCounters
double SteeringServoOutput
double PowerSensorV
double PowerSensorI
void TelemetryLogTime(int CommandPort)
References CommandPort, Time::dayOfMonth, Time::hour, Time::minute, Time::month, Time::second, Serials, Time::year.
Referenced by TelemetryLogging_Event_Decisions.
void TelemetryLogging_Event_Decisions(int CommandPort, word LoggingMask)
References CommandPort, StateValuesStruct::CommandState, CommandStateToString, DecisionEvent, DecisionEventReason, DecisionEventReasonToString, DecisionEventToString, Log_Decisions, StateValuesStruct::mission_index, Serials, TelemetryLogTime.
Referenced by CommandState_Processor, IsMissionStepComplete, LimitToSailingCourse, LoiterCalcCTS, SetTack, UpdateCourseToSteer.
String CommandStateToString(VesselCommandStateType CommandState)
References vcsFollowMission, vcsFullManual, vcsIdle, vcsLoiter, vcsPartialManual, vcsResetMissionIndex, vcsReturnToHome, vcsSetHome, vcsSteerMagneticCourse, vcsSteerWindCourse.
Referenced by ListParameter, SD_Logging_Event_Decisions, SendMessage, TelemetryLogging_Event_Decisions.
String DecisionEventToString(DecisionEventType DecisionEvent)
References deChangeCommandState, deEndOfMission, deHoldCourse, deIncrementMissionIndex, dePastWaypoint, deTackToPort, deTackToPortRunning, deTackToStarboard, deTackToStarboardRunning.
Referenced by SD_Logging_Event_Decisions, TelemetryLogging_Event_Decisions.
String DecisionEventReasonToString(DecisionEventReasonType DecisionEventReason)
References rApproachingWP, rFavouredTack, rLimitToSailingCourse, rManualIntervention, rNoChange, rNone, rPastBoundary, rPastDuration, rPastLoiterBoundary, rPastTime, rPastWaypoint, rUnkown.
Referenced by SD_Logging_Event_Decisions, TelemetryLogging_Event_Decisions.
String CourseTypeToString(SteeringCourseType CourseType)
References ctDirectToWayPoint, ctPortTack, ctStarboardTack.
Referenced by OLED_Logging, SD_Logging.
String CourseTypeToString(ManoeuvreStateType ManoeuvreState)
References mstCommence, mstComplete, mstNone, mstRunning.