USFS_IMU.cpp
float qt[2][4][2][4]
Referenced by IMU::computeIMU, EM7180::getQUAT.
int16_t accADC[2][3][2][3]
Referenced by IMU::computeIMU, FetchSentralData.
uint8_t eventStatus[2][2]
Referenced by FetchEventStatus, EM7180::initSensors, EM7180::WS_Resume.
uint8_t algostatus[2][2]
Referenced by FetchEventStatus, IMU_Read.
uint8_t Quat_flag[2][2]
Referenced by FetchEventStatus, FetchSentralData.
uint8_t Gyro_flag[2][2]
Referenced by FetchEventStatus, FetchSentralData.
uint8_t Acc_flag[2][2]
Referenced by FetchEventStatus, FetchSentralData.
uint8_t Mag_flag[2][2]
Referenced by FetchEventStatus, FetchSentralData.
uint8_t Baro_flag[2][2]
Referenced by FetchEventStatus, FetchSentralData.
int16_t gyroADC[2][3][2][3]
Referenced by FetchSentralData.
int16_t acc[2][3][2][3]
Referenced by EM7180::ACC_getADC.
int16_t acc_calADC[2][3][2][3]
Referenced by EM7180::ACC_Common.
int16_t magADC[2][3][2][3]
Referenced by FetchSentralData.
int16_t rawPressure[2][2]
Referenced by FetchSentralData.
int16_t rawTemperature[2][2]
Referenced by FetchSentralData.
float gyroData[2][3][2][3]
Referenced by FetchSentralData.
float LINaccData[2][3][2][3]
Referenced by FetchSentralData.
float magData[2][3][2][3]
Referenced by FetchSentralData.
float accData[2][3][2][3]
Referenced by FetchSentralData.
float pressure[2][2]
Referenced by FetchSentralData, IMU_Read.
float temperature[2][2]
Referenced by FetchSentralData, IMU_Read.
IMUStruct myIMU
I2Cdev* i2c_0
EM7180* Sentral_0
IMU* imu_0
HardwareSerial* Serials[][]
Referenced by IMU_Init.
void FetchEventStatus(I2Cdev *i2c_BUS, uint8_t sensorNUM)
References Acc_flag, algostatus, Baro_flag, EM7180_ADDRESS, EM7180_AlgorithmStatus, EM7180_EventStatus, eventStatus, Gyro_flag, Mag_flag, Quat_flag, I2Cdev::readByte.
Referenced by IMU_Read.
void FetchSentralData(EM7180 *em7180, IMU *IMu, uint8_t sensorNUM)
References EM7180::ACC_Common, Acc_flag, EM7180::ACC_getADC, accADC, accData, accLIN, Baro_flag, EM7180::Baro_getPress, EM7180::Baro_getTemp, IMU::computeIMU, DPS_PER_COUNT, G_PER_COUNT, Gyro_flag, EM7180::Gyro_getADC, gyroADC, gyroData, LINaccData, Mag_flag, EM7180::Mag_getADC, magADC, magData, pressure, Quat_flag, rawPressure, rawTemperature, SENTRAL_UT_PER_COUNT, temperature.
Referenced by IMU_Read.
void IMU_Init(int CommandPort)
References CommandPort, EM7180::initSensors, Serials.
void IMU_Read(void)
References IMUStruct::Algorithm_Status, algostatus, angle, IMUStruct::baro_pressure, IMUStruct::baro_temperature, FetchEventStatus, FetchSentralData, heading, IMUStruct::heading, IMUStruct::pitch, pressure, IMUStruct::roll, temperature, wrap_360.
void IMU_Save_Cal(void)
References EM7180::Save_Sentral_WS_params.
Referenced by CLI_Processor.