TinyGPSPlus
@5
TinyGPSLocation TinyGPSPlus::location
Referenced by endOfTermHandler, GPS_Read.
TinyGPSDate TinyGPSPlus::date
Referenced by endOfTermHandler, GPS_Read, GPS_Read_Time.
TinyGPSTime TinyGPSPlus::time
Referenced by endOfTermHandler, GPS_Read, GPS_Read_Time.
TinyGPSSpeed TinyGPSPlus::speed
Referenced by endOfTermHandler, GPS_Read.
TinyGPSCourse TinyGPSPlus::course
Referenced by endOfTermHandler, GPS_Read.
TinyGPSAltitude TinyGPSPlus::altitude
Referenced by endOfTermHandler.
TinyGPSInteger TinyGPSPlus::satellites
Referenced by endOfTermHandler.
TinyGPSHDOP TinyGPSPlus::hdop
Referenced by endOfTermHandler.
uint8_t TinyGPSPlus::parity
Referenced by encode, endOfTermHandler.
bool TinyGPSPlus::isChecksumTerm
Referenced by encode, endOfTermHandler.
char TinyGPSPlus::term[_GPS_MAX_FIELD_SIZE][_GPS_MAX_FIELD_SIZE]
Referenced by encode, endOfTermHandler, parseDecimal, TinyGPSPlus.
uint8_t TinyGPSPlus::curSentenceType
Referenced by encode, endOfTermHandler.
uint8_t TinyGPSPlus::curTermNumber
Referenced by encode, endOfTermHandler.
uint8_t TinyGPSPlus::curTermOffset
Referenced by encode.
bool TinyGPSPlus::sentenceHasFix
Referenced by encode, endOfTermHandler.
TinyGPSCustom* TinyGPSPlus::customElts
Referenced by endOfTermHandler, insertCustom.
TinyGPSCustom* TinyGPSPlus::customCandidates
Referenced by endOfTermHandler.
uint32_t TinyGPSPlus::encodedCharCount
Referenced by charsProcessed, encode.
uint32_t TinyGPSPlus::sentencesWithFixCount
Referenced by endOfTermHandler, sentencesWithFix.
uint32_t TinyGPSPlus::failedChecksumCount
Referenced by endOfTermHandler, failedChecksum.
uint32_t TinyGPSPlus::passedChecksumCount
Referenced by endOfTermHandler, passedChecksum.
friend class TinyGPSCustom
TinyGPSPlus::TinyGPSPlus()
References term.
bool TinyGPSPlus::encode(char c)
References curSentenceType, curTermNumber, curTermOffset, encodedCharCount, endOfTermHandler, GPS_SENTENCE_OTHER, isChecksumTerm, parity, sentenceHasFix, term.
Referenced by GPS_Read, GPS_Read_Time, operator<<.
TinyGPSPlus& TinyGPSPlus::operator<<(char c)
References encode.
uint32_t TinyGPSPlus::charsProcessed() const
References encodedCharCount.
uint32_t TinyGPSPlus::sentencesWithFix() const
References sentencesWithFixCount.
uint32_t TinyGPSPlus::failedChecksum() const
References failedChecksumCount.
uint32_t TinyGPSPlus::passedChecksum() const
References passedChecksumCount.
static const char* TinyGPSPlus::libraryVersion()
References _GPS_VERSION.
double TinyGPSPlus::distanceBetween(double lat1, double long1, double lat2, double long2)
References radians, sq.
double TinyGPSPlus::courseTo(double lat1, double long1, double lat2, double long2)
References degrees, radians.
const char * TinyGPSPlus::cardinal(double course)
int32_t TinyGPSPlus::parseDecimal(const char *term)
References term.
Referenced by TinyGPSDecimal::set, TinyGPSTime::setTime.
void TinyGPSPlus::parseDegrees(const char *term, RawDegrees &deg)
References RawDegrees::billionths, RawDegrees::deg, RawDegrees::negative.
Referenced by TinyGPSLocation::setLatitude, TinyGPSLocation::setLongitude.
void TinyGPSPlus::insertCustom(TinyGPSCustom *pElt, const char *sentenceName, int index)
References customElts, TinyGPSCustom::next.
Referenced by TinyGPSCustom::begin.
int TinyGPSPlus::fromHex(char a)
Referenced by endOfTermHandler.
bool TinyGPSPlus::endOfTermHandler()
References _GNGGAterm, _GNRMCterm, _GPGGAterm, _GPRMCterm, altitude, COMBINE, TinyGPSLocation::commit, TinyGPSDate::commit, TinyGPSTime::commit, TinyGPSInteger::commit, course, curSentenceType, curTermNumber, customCandidates, customElts, date, failedChecksumCount, fromHex, GPS_SENTENCE_GPGGA, GPS_SENTENCE_GPRMC, GPS_SENTENCE_OTHER, hdop, isChecksumTerm, location, RawDegrees::negative, TinyGPSCustom::next, parity, passedChecksumCount, TinyGPSLocation::rawNewLatData, TinyGPSLocation::rawNewLngData, satellites, sentenceHasFix, TinyGPSCustom::sentenceName, sentencesWithFixCount, TinyGPSInteger::set, TinyGPSDate::setDate, TinyGPSLocation::setLatitude, TinyGPSLocation::setLongitude, TinyGPSTime::setTime, speed, term, TinyGPSCustom::termNumber, time.
Referenced by encode.