I2CGPS
uint8_t I2CGPS::gpsData[MAX_PACKET_SIZE][MAX_PACKET_SIZE]
Referenced by check, read.
TwoWire* I2CGPS::_i2cPort
Referenced by begin, check, sendMTKpacket.
uint8_t I2CGPS::_i2caddr
boolean I2CGPS::_printDebug
Referenced by check, disableDebugging, enableDebugging, sendMTKpacket.
Stream* I2CGPS::_debugSerial
Referenced by check, enableDebugging, sendMTKpacket.
uint8_t I2CGPS::_head
Referenced by available, begin, check, read.
uint8_t I2CGPS::_tail
Referenced by available, begin, check, read.
boolean I2CGPS::begin(TwoWire &wirePort=Wire, uint32_t i2cSpeed=I2C_SPEED_STANDARD)
References _head, _i2cPort, _tail, MT333x_ADDR.
Referenced by GPS_Init.
void I2CGPS::check()
References _debugSerial, _head, _i2cPort, _printDebug, _tail, gpsData, MAX_PACKET_SIZE, MT333x_ADDR.
Referenced by available.
uint8_t I2CGPS::available()
References _head, _tail, check, MAX_PACKET_SIZE.
Referenced by GPS_Read, GPS_Read_Time.
uint8_t I2CGPS::read()
References _head, _tail, gpsData, MAX_PACKET_SIZE.
Referenced by GPS_Read, GPS_Read_Time.
void I2CGPS::enableDebugging(Stream &debugPort=Serial)
References _debugSerial, _printDebug.
void I2CGPS::disableDebugging()
References _printDebug.
boolean I2CGPS::sendMTKpacket(String command)
References _debugSerial, _i2cPort, _printDebug, MT333x_ADDR.
String I2CGPS::createMTKpacket(uint16_t packetType, String dataField)
References calcCRCforMTK.
String I2CGPS::calcCRCforMTK(String sentence)
Referenced by createMTKpacket.