MPU9250
Ascale
Gscale
Mscale
uint8_t MPU9250::Gscale
uint8_t MPU9250::Ascale
uint8_t MPU9250::Mscale
uint8_t MPU9250::Mmode
Referenced by initAK8963.
float MPU9250::pitch
Referenced by WingSailAngleSensor_Read.
float MPU9250::yaw
float MPU9250::roll
Referenced by WingSailAngleSensor_Read.
float MPU9250::temperature
Referenced by WingSailAngleSensor_Read.
int16_t MPU9250::tempCount
Referenced by WingSailAngleSensor_Read.
uint32_t MPU9250::delt_t
Referenced by WingSailAngleSensor_Read.
uint32_t MPU9250::count
Referenced by WingSailAngleSensor_Read.
uint32_t MPU9250::sumCount
Referenced by updateTime, WingSailAngleSensor_Read.
float MPU9250::deltat
Referenced by updateTime.
float MPU9250::sum
Referenced by updateTime, WingSailAngleSensor_Read.
uint32_t MPU9250::lastUpdate
Referenced by updateTime.
uint32_t MPU9250::firstUpdate
uint32_t MPU9250::Now
Referenced by updateTime.
int16_t MPU9250::gyroCount[3][3]
Referenced by WingSailAngleSensor_Read.
int16_t MPU9250::magCount[3][3]
Referenced by WingSailAngleSensor_Read.
float MPU9250::aRes
Referenced by getAres, WingSailAngleSensor_Read.
float MPU9250::gRes
Referenced by getGres, WingSailAngleSensor_Read.
float MPU9250::mRes
Referenced by getMres, WingSailAngleSensor_Read.
float MPU9250::ax
Referenced by WingSailAngleSensor_Read.
float MPU9250::ay
Referenced by WingSailAngleSensor_Read.
float MPU9250::az
Referenced by WingSailAngleSensor_Read.
float MPU9250::gx
Referenced by WingSailAngleSensor_Read.
float MPU9250::gy
Referenced by WingSailAngleSensor_Read.
float MPU9250::gz
Referenced by WingSailAngleSensor_Read.
float MPU9250::mx
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, OLED_Logging, WingSailAngleSensor_Read.
float MPU9250::my
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, OLED_Logging, WingSailAngleSensor_Read.
float MPU9250::mz
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, WingSailAngleSensor_Read.
float MPU9250::magCalibration[3][3]
Referenced by WingSailAngleSensor_Init, WingSailAngleSensor_Read.
float MPU9250::magbias[3][3]
Referenced by WingSailAngleSensor_Read.
float MPU9250::gyroBias[3][3]
Referenced by WingSailAngleSensor_Init.
float MPU9250::accelBias[3][3]
Referenced by WingSailAngleSensor_Init.
float MPU9250::SelfTest[6][6]
Referenced by WingSailAngleSensor_Init.
int16_t MPU9250::accelCount[3][3]
Referenced by WingSailAngleSensor_Read.
float MPU9250::mx_min
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, Load_IMU_Calibation_Values, OLED_Logging, WingSailAngleSensor_Read.
float MPU9250::mx_max
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, Load_IMU_Calibation_Values, OLED_Logging, WingSailAngleSensor_Read.
float MPU9250::my_min
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, Load_IMU_Calibation_Values, OLED_Logging, WingSailAngleSensor_Read.
float MPU9250::my_max
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, Load_IMU_Calibation_Values, OLED_Logging, WingSailAngleSensor_Read.
float MPU9250::mz_min
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, Load_IMU_Calibation_Values, WingSailAngleSensor_Read.
float MPU9250::mz_max
Referenced by IMU_Mag_Calibrate, IMU_Mag_Init, Load_IMU_Calibation_Values, WingSailAngleSensor_Read.
int MPU9250::MagneticAngle
Referenced by GetApparentWind, OLED_Logging, WingSailAngleSensor_Read.
bool MPU9250::MagneticAngleCalibrationMode
Referenced by CLI_Processor, WingSailAngleSensor_Init, WingSailAngleSensor_Read.
bool MPU9250::Initialsed
Referenced by OLED_Logging, SendMessage, WingSailAngleSensor_Init.
void MPU9250::getMres()
References MFS_14BITS, MFS_16BITS, mRes.
Referenced by WingSailAngleSensor_Read.
void MPU9250::getGres()
References GFS_1000DPS, GFS_2000DPS, GFS_250DPS, GFS_500DPS, gRes.
Referenced by WingSailAngleSensor_Read.
void MPU9250::getAres()
References AFS_16G, AFS_2G, AFS_4G, AFS_8G, aRes.
Referenced by WingSailAngleSensor_Read.
void MPU9250::readAccelData(int16_t *)
References ACCEL_XOUT_H, MPU9250_ADDRESS, readBytes.
Referenced by WingSailAngleSensor_Read.
void MPU9250::readGyroData(int16_t *)
References GYRO_XOUT_H, MPU9250_ADDRESS, readBytes.
Referenced by WingSailAngleSensor_Read.
void MPU9250::readMagData(int16_t *)
References AK8963_ADDRESS, AK8963_ST1, AK8963_XOUT_L, readByte, readBytes.
Referenced by WingSailAngleSensor_Read.
int16_t MPU9250::readTempData()
References MPU9250_ADDRESS, readBytes, TEMP_OUT_H.
Referenced by WingSailAngleSensor_Read.
void MPU9250::updateTime()
References deltat, lastUpdate, Now, sum, sumCount.
Referenced by WingSailAngleSensor_Read.
void MPU9250::initAK8963(float *)
References AK8963_ADDRESS, AK8963_ASAX, AK8963_CNTL, Mmode, readBytes, writeByte.
Referenced by WingSailAngleSensor_Init.
void MPU9250::initMPU9250()
References ACCEL_CONFIG, ACCEL_CONFIG2, CONFIG, GYRO_CONFIG, INT_ENABLE, INT_PIN_CFG, MPU9250_ADDRESS, PWR_MGMT_1, readByte, SMPLRT_DIV, writeByte.
Referenced by WingSailAngleSensor_Init.
void MPU9250::calibrateMPU9250(float *gyroBias, float *accelBias)
References ACCEL_CONFIG, CONFIG, FIFO_COUNTH, FIFO_EN, FIFO_R_W, GYRO_CONFIG, I2C_MST_CTRL, INT_ENABLE, MPU9250_ADDRESS, PWR_MGMT_1, PWR_MGMT_2, readBytes, SMPLRT_DIV, USER_CTRL, writeByte, XA_OFFSET_H, XA_OFFSET_L, XG_OFFSET_H, XG_OFFSET_L, YA_OFFSET_H, YA_OFFSET_L, YG_OFFSET_H, YG_OFFSET_L, ZA_OFFSET_H, ZA_OFFSET_L, ZG_OFFSET_H, ZG_OFFSET_L.
Referenced by WingSailAngleSensor_Init.
void MPU9250::MPU9250SelfTest(float *destination)
References ACCEL_CONFIG, ACCEL_CONFIG2, ACCEL_XOUT_H, CONFIG, GYRO_CONFIG, GYRO_XOUT_H, MPU9250_ADDRESS, readByte, readBytes, SELF_TEST_X_ACCEL, SELF_TEST_X_GYRO, SELF_TEST_Y_ACCEL, SELF_TEST_Y_GYRO, SELF_TEST_Z_ACCEL, SELF_TEST_Z_GYRO, SMPLRT_DIV, writeByte.
Referenced by WingSailAngleSensor_Init.
void MPU9250::writeByte(uint8_t, uint8_t, uint8_t)
Referenced by calibrateMPU9250, initAK8963, initMPU9250, MPU9250SelfTest.
uint8_t MPU9250::readByte(uint8_t, uint8_t)
Referenced by initMPU9250, MPU9250SelfTest, readMagData, WingSailAngleSensor_Init, WingSailAngleSensor_Read.
void MPU9250::readBytes(uint8_t, uint8_t, uint8_t, uint8_t *)
Referenced by calibrateMPU9250, initAK8963, MPU9250SelfTest, readAccelData, readGyroData, readMagData, readTempData.