eepromAnything.h
int EEPROM_write(int ee, const T &value)
Referenced by Save_EEPROM_ConfigValues, Save_EEPROM_Mission, Save_EEPROM_StateValues, Save_EEPROM_VesselUsage.
int EEPROM_read(int ee, T &value)
Referenced by Load_EEPROM_ConfigValues, load_EEPROM_Mission, Load_EEPROM_StateValues, Load_EEPROM_VesselUsage.