location.h
float get_distance(const struct Location &loc1, const struct Location &loc2)
References Location::lat, Location::lng, LOCATION_SCALING_FACTOR, longitude_scale, pythagorous2.
Referenced by get_CTE, get_distance_cm, location_passed_point, reached_waypoint_point.
int get_bearing(const struct Location &loc1, const struct Location &loc2)
References Location::lat, Location::lng, longitude_scale.
Referenced by LoiterCalcCTS, NavigationUpdate_SlowData.
float get_bearingf(const struct Location &loc1, const struct Location &loc2)
References Location::lat, Location::lng, longitude_scale.
Referenced by get_CTE.
int wrap_180(int angle)
References angle.
Referenced by AWA_Calculated, GetFavouredTack, LimitToSailingCourse, NavigationUpdate_FastData, NavigationUpdate_SlowData, SteeringFastUpdate, UpdateTurnHeadingV2.
float wrap_360(float angle)
References angle.
Referenced by CalculateSailingCTS, CommandState_Processor, GetTrueWind, IMU_Read, LoiterCalcCTS, NavigationUpdate_FastData, NavigationUpdate_SlowData, OLED_Logging, SteerCloseHauled, SteerDeepRunning, UpdateCourseToSteer, UpdateTurnHeadingV2.
bool location_passed_point(const struct Location &location, const struct Location &point1, const struct Location &point2)
References angle, degrees, get_distance, Location::lat, Location::lng.
Referenced by reached_waypoint_point.
bool reached_waypoint_point(const struct Location &location, const struct Location &point1, const struct Location &point2, int WP_Boundary)
References get_distance, location_passed_point.
Referenced by NavigationUpdate_SlowData.
int get_CTE(const struct Location &location, const struct Location &point1, const struct Location &point2)
References get_bearingf, get_distance.
Referenced by NavigationUpdate_SlowData.