TinyGPSDecimal
friend class TinyGPSPlus
bool TinyGPSDecimal::valid
Referenced by age, commit, isValid.
bool TinyGPSDecimal::updated
Referenced by commit, isUpdated, value.
uint32_t TinyGPSDecimal::lastCommitTime
Referenced by age, commit.
int32_t TinyGPSDecimal::val
Referenced by commit, value.
int32_t TinyGPSDecimal::newval
Referenced by commit, set.
bool TinyGPSDecimal::isValid() const
References valid.
bool TinyGPSDecimal::isUpdated() const
References updated.
uint32_t TinyGPSDecimal::age() const
References lastCommitTime, valid.
int32_t TinyGPSDecimal::value()
References updated, val.
Referenced by TinyGPSCourse::deg, TinyGPSAltitude::feet, TinyGPSHDOP::hdop, TinyGPSAltitude::kilometers, TinyGPSSpeed::kmph, TinyGPSSpeed::knots, TinyGPSAltitude::meters, TinyGPSAltitude::miles, TinyGPSSpeed::mph, TinyGPSSpeed::mps.
TinyGPSDecimal::TinyGPSDecimal()
void TinyGPSDecimal::commit()
References lastCommitTime, newval, updated, val, valid.
void TinyGPSDecimal::set(const char *term)
References newval, TinyGPSPlus::parseDecimal.