AP_Math.h
M_PI_F
M_PI_2
DEG_TO_RAD_DOUBLE
RAD_TO_DEG_DOUBLE
RadiansToCentiDegrees
GRAVITY_MSS
RADIUS_OF_EARTH
ROTATION_COMBINATION_SUPPORT
LATLON_TO_M
LATLON_TO_CM
WGS84_A
WGS84_IF
WGS84_F
WGS84_B
WGS84_E
max
min
Referenced by Adafruit_GFX_Button::drawButton.
float safe_asin(float v)
float safe_sqrt(float v)
float fast_atan(float v)
float fast_atan2(float y, float x)
References FAST_ATAN2_PIBY2_FLOAT.
float longitude_scale(const struct Location &loc)
References constrain_float, Location::lat.
Referenced by get_bearing, get_bearingf, get_distance, location_offset.
float get_distance(const struct Location &loc1, const struct Location &loc2)
Referenced by LoiterCalcCTS, NavigationUpdate_SlowData.
int32_t get_bearing_cd(const struct Location &loc1, const struct Location &loc2)
bool location_passed_point(const struct Location &location, const struct Location &point1, const struct Location &point2)
Referenced by LoiterCalcCTS.
void location_update(struct Location &loc, float bearing, float distance)
References location_offset, radians.
Referenced by CLI_Processor, CommandState_Processor, LoiterCalcCTS.
void location_offset(struct Location &loc, float ofs_north, float ofs_east)
References Location::lat, Location::lng, LOCATION_SCALING_FACTOR_INV, longitude_scale.
Referenced by location_update.
int32_t wrap_360_cd(int32_t error)
int32_t wrap_180_cd(int32_t error)
float constrain_float(float amt, float low, float high)
Referenced by longitude_scale.
int16_t constrain_int16(int16_t amt, int16_t low, int16_t high)
int32_t constrain_int32(int32_t amt, int32_t low, int32_t high)
float pythagorous2(float a, float b)
References sq.
Referenced by get_distance, Vector2< T >::length.
float pythagorous3(float a, float b, float c)
References sq.