AP_Math.cpp
FAST_ATAN2_PIBY2_FLOAT
Referenced by fast_atan2.
float safe_asin(float v)
float safe_sqrt(float v)
float fast_atan(float v)
float fast_atan2(float y, float x)
References FAST_ATAN2_PIBY2_FLOAT.
float constrain_float(float amt, float low, float high)
Referenced by longitude_scale.
int16_t constrain_int16(int16_t amt, int16_t low, int16_t high)
int32_t constrain_int32(int32_t amt, int32_t low, int32_t high)
float pythagorous2(float a, float b)
References sq.
Referenced by get_distance, Vector2< T >::length.
float pythagorous3(float a, float b, float c)
References sq.