BluetoothConnection.h
BTStateType
void Bluetooth_Init(int BluetoothPort)
References BluetoothStatePin, configValuesType::BTPortBaudRate, Serials.
void BluetoothInitialiseConnection(int BluetoothPort)
References BTState, Initialised, Initialising, Serials.
Referenced by BluetoothManageConnection.
void BluetoothManageConnection(int BluetoothPort)
References BluetoothInitialiseConnection, configValuesType::BluetoothPort, BluetoothStatePin, BTState, Connected, Connecting, Idle, Initialised, Initialising, Querying, Serials.
char* GetBTStatus(BTStateType BTState)
References Connected, Connecting, Idle, Initialised, Initialising, Querying.
Referenced by CLI_Processor, OLED_Logging, SD_Logging.
void BT_CLI_Process_Message(int BluetoothPort)
References BT_CLI_i, BT_CLI_Msg, BT_CLI_Processor, Serials.
void BT_CLI_Processor(int BluetoothPort)
References BT_CLI_Msg, CommandPort, Serials.
Referenced by BT_CLI_Process_Message.