BluetoothConnection.cpp
byte BluetoothStatePin
Referenced by Bluetooth_Init, BluetoothManageConnection.
BTStateType BTState
Referenced by BluetoothInitialiseConnection, BluetoothManageConnection.
HardwareSerial* Serials[][]
Referenced by Bluetooth_Init, BluetoothInitialiseConnection, BluetoothManageConnection, BT_CLI_Process_Message, BT_CLI_Processor.
configValuesType Configuration
int CommandPort
Referenced by BT_CLI_Processor, CLI_Process_Message, CLI_Processor, GPS_Init, IMU_Init, ListParameter, Load_ConfigValues, SendMessage, SendMissionStep, ShowCommandState, TelemetryLogging_Event_Decisions, TelemetryLogTime, WingSailAngleSensor_Init.
char BT_CLI_Msg[50][50]
Referenced by BT_CLI_Process_Message, BT_CLI_Processor.
int BT_CLI_i
Referenced by BT_CLI_Process_Message.
void Bluetooth_Init(int BluetoothPort)
References BluetoothStatePin, configValuesType::BTPortBaudRate, Serials.
void BluetoothManageConnection(int BluetoothPort)
References BluetoothInitialiseConnection, configValuesType::BluetoothPort, BluetoothStatePin, BTState, Connected, Connecting, Idle, Initialised, Initialising, Querying, Serials.
void BluetoothInitialiseConnection(int BluetoothPort)
References BTState, Initialised, Initialising, Serials.
Referenced by BluetoothManageConnection.
char* GetBTStatus(BTStateType BTState)
References Connected, Connecting, Idle, Initialised, Initialising, Querying.
Referenced by CLI_Processor, OLED_Logging, SD_Logging.
void BT_CLI_Process_Message(int BluetoothPort)
References BT_CLI_i, BT_CLI_Msg, BT_CLI_Processor, Serials.
void BT_CLI_Processor(int BluetoothPort)
References BT_CLI_Msg, CommandPort, Serials.
Referenced by BT_CLI_Process_Message.