GPS.cpp
TinyGPSPlus gps
NavigationDataType NavData
HardwareSerial* Serials[][]
Referenced by GPS_Init.
configValuesType Configuration
I2CGPS myI2CGPS
long GPS_Last_Loc
Referenced by GPS_LocationIs_Valid, GPS_Read, GPS_Temp_Read, SD_Logging.
long GPS_Last_Message
Referenced by GPS_Read, GPS_Temp_Read, SD_Logging.
bool UseSimulatedGPS
Referenced by GPS_LocationIs_Valid.
Time CurrentUTCTime
Time CurrentLocalTime
void GPS_Init(int CommandPort)
References I2CGPS::begin, CommandPort, GPS_Read, GPS_Read_Time, Serials, configValuesType::timezone_offset, UpdateLocalTimeFromGPSTime.
void GPS_Read()
References I2CGPS::available, NavigationDataType::COG, TinyGPSPlus::course, NavigationDataType::Currentloc, NavigationDataType::CurrentLocTimeStamp, TinyGPSPlus::date, TinyGPSDate::day, Time::dayOfMonth, TinyGPSCourse::deg, TinyGPSPlus::encode, GPS_Last_Loc, GPS_Last_Message, Time::hour, TinyGPSTime::hour, TinyGPSSpeed::knots, Location::lat, TinyGPSLocation::lat, Location::lng, TinyGPSLocation::lng, TinyGPSPlus::location, Time::minute, TinyGPSTime::minute, Time::month, TinyGPSDate::month, TinyGPSSpeed::mps, I2CGPS::read, Time::second, TinyGPSTime::second, NavigationDataType::SOG_knt, NavigationDataType::SOG_mps, TinyGPSPlus::speed, TinyGPSPlus::time, Time::year, TinyGPSDate::year.
Referenced by GPS_Init.
void GPS_Read_Time()
References I2CGPS::available, TinyGPSPlus::date, TinyGPSDate::day, Time::dayOfMonth, TinyGPSPlus::encode, Time::hour, TinyGPSTime::hour, Time::minute, TinyGPSTime::minute, Time::month, TinyGPSDate::month, I2CGPS::read, Time::second, TinyGPSTime::second, TinyGPSPlus::time, Time::year, TinyGPSDate::year.
Referenced by GPS_Init.
void UpdateLocalTimeFromGPSTime(byte timezone_offset)
References Time::dayOfMonth, DaysInMonth, Time::hour, Time::minute, Time::month, Time::second, Time::year.
Referenced by GPS_Init.
byte DaysInMonth(byte month, byte year)
Referenced by UpdateLocalTimeFromGPSTime.
bool GPS_LocationIs_Valid(Location TestLoc)
References GPS_Last_Loc, Location::lat, Location::lng, UseSimulatedGPS.
Referenced by MissionUpdate, NavigationUpdate_SlowData, OLED_Logging, SD_Logging, SteeringFastUpdate, wingsail_update.
bool GPS_TimeIs_Valid()
References Time::month.
Referenced by Check_GPS_TimeStatus.