Mission.cpp
LoiterStruct LoiterData
NavigationDataType NavData
int CommandPort
Referenced by IsMissionStepComplete.
StateValuesStruct StateValues
MissionValuesStruct MissionValues
Time CurrentLocalTime
configValuesType Configuration
DecisionEventType DecisionEvent
Referenced by IsMissionStepComplete.
DecisionEventReasonType DecisionEventReason
Referenced by IsMissionStepComplete.
void MissionUpdate(void)
References StateValuesStruct::CommandState, MissionCommand::controlMask, NavigationDataType::Currentloc, GPS_LocationIs_Valid, IsMissionStepComplete, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, MissionValuesStruct::MissionCommandStartTime, MissionValuesStruct::MissionList, PowerControl, NavigationDataType::prev_WP, Save_EEPROM_StateValues, SD_Logging_Event_MissionStep, StateValuesStruct::StartingMission, UpdatePrevNextWP, vcsFollowMission.
bool IsMissionStepComplete(void)
References MissionCommand::cmd, CommandPort, StateValuesStruct::CommandState, ctGotoWaypoint, ctLoiter, ctLoiterUntil, ctReturnToHome, ctSteerWindCourse, DecisionEvent, DecisionEventReason, deEndOfMission, deIncrementMissionIndex, MissionCommand::duration, StateValuesStruct::home_is_set, Time::hour, Time::minute, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, MissionValuesStruct::MissionCommandStartTime, MissionValuesStruct::MissionList, NavigationDataType::PastWP, RCPowerOn, rPastDuration, rPastTime, rPastWaypoint, SD_Logging_Event_Decisions, configValuesType::SDCardLoggingMask, TelemetryLogging_Event_Decisions, configValuesType::TelemetryLoggingMask, TelemetryPowerOn, vcsLoiter, vcsReturnToHome.
Referenced by MissionUpdate.
void UpdatePrevNextWP(void)
References MissionCommand::boundary, MissionCommand::cmd, ctGotoWaypoint, ctLoiter, ctLoiterUntil, ctReturnToHome, ctSteerWindCourse, NavigationDataType::Currentloc, StateValuesStruct::home, LoiterStruct::loiterCentreLocation, LoiterStruct::loiterLocationPrevious, LoiterStruct::LoiterRadius, LoiterStruct::LoiterState, lsApproach, NavigationDataType::MaxCTE, StateValuesStruct::mission_index, MissionValuesStruct::MissionList, NavigationDataType::next_WP, NavigationDataType::next_WP_valid, NavigationDataType::prev_WP, MissionCommand::SteerAWA, StateValuesStruct::SteerWindAngle, MissionCommand::waypoint.
Referenced by MissionUpdate.
void set_next_WP_for_display()
References MissionCommand::boundary, StateValuesStruct::CommandState, NavigationDataType::MaxCTE, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, MissionValuesStruct::MissionList, NavigationDataType::next_WP, vcsFollowMission, MissionCommand::waypoint.
Referenced by CLI_Processor.