PowerManagement.h
void InitPowerManagement(void)
References GPS_PowerPin, OLED_PowerPin, RC_PowerPin, RCPowerOn, Telemetry_PowerPin, TelemetryPowerOn.
void TelemetryPowerOn(boolean PowerOn)
References Telemetry_PowerPin.
Referenced by CLI_Processor, InitPowerManagement, IsMissionStepComplete, PowerControl.
void RCPowerOn(boolean PowerOn)
References RC_PowerPin.
Referenced by CLI_Processor, InitPowerManagement, IsMissionStepComplete, PowerControl.
void PowerControl(int controlMask)
References RCPowerOn, TelemetryPowerOn.
Referenced by MissionUpdate.