SDCardLogFile.cpp
SD_Card_CS_PIN
Referenced by SD_Logging_Init.
SdFat sd
Referenced by SD_Logging_Init.
SdFile LogFile
Referenced by Check_LogFileSize, CloseThenOpenLogFile, LogTime, LogTimeHeader, OpenSDLogFile, SD_Logging, SD_Logging_Event_Decisions, SD_Logging_Event_Messsage, SD_Logging_Event_MissionStep, SD_Logging_Event_ParameterChange, SD_Logging_Event_Usage, SD_Logging_OpenFile.
int CommandPort
Referenced by CloseThenOpenLogFile, SD_Logging, SD_Logging_Init, SD_Logging_OpenFile.
StateValuesStruct StateValues
NavigationDataType NavData
IMUStruct myIMU
long loop_period_us
Referenced by SD_Logging.
long GPS_Last_Loc
Referenced by SD_Logging.
long GPS_Last_Message
Referenced by SD_Logging.
bool UseSimulatedGPS
Referenced by SD_Logging.
configValuesType Configuration
HardwareSerial* Serials[][]
Referenced by SD_Logging_Init, SD_Logging_OpenFile.
bool SD_Card_Present
Referenced by SD_Logging_Init.
Time CurrentLocalTime
DecisionEventType DecisionEvent
Referenced by SD_Logging_Event_Decisions.
DecisionEventReasonType DecisionEventReason
Referenced by SD_Logging_Event_Decisions.
int DecisionEventValue
Referenced by SD_Logging_Event_Decisions.
VesselUsageCountersStruct VesselUsageCounters
double SteeringServoOutput
Referenced by SD_Logging.
double PowerSensorV
Referenced by SD_Logging.
double PowerSensorI
Referenced by SD_Logging.
BTStateType BTState
Referenced by SD_Logging.
WingSailType WingSail
MissionValuesStruct MissionValues
char Version[][]
Referenced by SD_Logging_OpenFile.
void dateTime(uint16_t *date, uint16_t *time)
References Time::dayOfMonth, Time::hour, Time::minute, Time::month, Time::second, Time::year.
Referenced by SD_Logging_Init.
void LogTimeHeader(void)
References LogFile, configValuesType::SDCardLogDelimiter.
Referenced by SD_Logging_OpenFile.
void SD_Logging_Init(int CommandPort)
References CommandPort, dateTime, sd, SD_Card_CS_PIN, SD_Card_Present, Serials.
void SD_Logging_OpenFile(int CommandPort, word LoggingMask)
References CommandPort, Time::dayOfMonth, Time::hour, Log_Attitude, Log_Decisions, Log_Environment, Log_GPS, Log_Location, Log_Navigation, Log_Sailing, Log_ServoOut, Log_Situation, Log_System, Log_Usage, Log_Voltages, Log_Waypoints, LogFile, LogTimeHeader, Time::minute, Time::month, OpenSDLogFile, SD_Logging_Event_Messsage, SD_Logging_Event_Usage, configValuesType::SDCardLogDelimiter, configValuesType::SDCardLoggingMask, Serials, Version.
Referenced by CloseThenOpenLogFile.
void OpenSDLogFile(String LogFileName)
References LogFile.
Referenced by SD_Logging_OpenFile.
void LogTime(void)
References Time::dayOfMonth, Time::hour, LogFile, Time::minute, Time::month, configValuesType::SDCardLogDelimiter, Time::second, Time::year.
Referenced by SD_Logging, SD_Logging_Event_Decisions, SD_Logging_Event_Messsage, SD_Logging_Event_MissionStep, SD_Logging_Event_ParameterChange, SD_Logging_Event_Usage.
void SD_Logging(word LoggingMask)
References IMUStruct::Algorithm_Status, WingSailType::Angle, NavigationDataType::AWA, IMUStruct::baro_pressure, IMUStruct::baro_temperature, BTState, NavigationDataType::BTW, NavigationDataType::CDA, Check_GPS_TimeStatus, Check_LogFileSize, NavigationDataType::COG, CommandPort, NavigationDataType::CourseType, CourseTypeToString, NavigationDataType::CTE, NavigationDataType::CTS, NavigationDataType::Currentloc, NavigationDataType::DTW, GetBTStatus, GPS_Last_Loc, GPS_Last_Message, GPS_LocationIs_Valid, NavigationDataType::HDG, NavigationDataType::HDG_Err, NavigationDataType::HDG_Mag, NavigationDataType::IsBTWSailable, Location::lat, Location::lng, Log_Attitude, Log_Environment, Log_GPS, Log_Location, Log_Navigation, Log_Sailing, Log_ServoOut, Log_Situation, Log_System, Log_Voltages, Log_Waypoints, LogFile, LogTime, loop_period_us, NavigationDataType::MaxCTE, NavigationDataType::next_WP, IMUStruct::pitch, PowerSensorI, PowerSensorV, NavigationDataType::prev_WP, NavigationDataType::RLB, IMUStruct::roll, NavigationDataType::ROLL_Avg, configValuesType::SDCardLogDelimiter, configValuesType::SDCardLoggingMask, NavigationDataType::SOG_mps, SteeringServoOutput, NavigationDataType::TackDuration, NavigationDataType::TargetHDG, WingSailType::TrimTabAngle, NavigationDataType::TurnHDG, NavigationDataType::TWD, NavigationDataType::TWS, UseSimulatedGPS.
void Check_LogFileSize(int CommandPort, word LoggingMask)
References CloseThenOpenLogFile, LogFile, configValuesType::MaxFileSize.
Referenced by SD_Logging.
void CloseThenOpenLogFile(word LoggingMask)
References CommandPort, LogFile, SD_Logging_OpenFile.
Referenced by Check_GPS_TimeStatus, Check_LogFileSize.
void SD_Logging_Event_Decisions(word LoggingMask)
References StateValuesStruct::CommandState, CommandStateToString, DecisionEvent, DecisionEventReason, DecisionEventReasonToString, DecisionEventToString, DecisionEventValue, Log_Decisions, LogFile, LogTime, StateValuesStruct::mission_index, configValuesType::SDCardLogDelimiter.
Referenced by CommandState_Processor, IsMissionStepComplete, LimitToSailingCourse, LoiterCalcCTS, SetTack, UpdateCourseToSteer.
void SD_Logging_Event_ParameterChange(int ParameterIndex, char ParameterValue[12])
References LogFile, LogTime, configValuesType::SDCardLogDelimiter.
Referenced by CLI_Processor.
void SD_Logging_Event_Messsage(String message)
References LogFile, LogTime.
Referenced by SD_Logging_OpenFile.
void SD_Logging_Event_MissionStep(int mission_index)
References MissionCommand::boundary, MissionCommand::cmd, MissionCommand::controlMask, MissionCommand::duration, GetMissionCommandString, Location::lat, Location::lng, LogFile, LogTime, MissionValuesStruct::MissionList, configValuesType::SDCardLogDelimiter, MissionCommand::SteerAWA, MissionCommand::TrimTabAngle, MissionCommand::waypoint.
Referenced by MissionUpdate.
void SD_Logging_Event_Usage(word LoggingMask)
References VesselUsageCountersStruct::intervalCounter, Log_Usage, LogFile, LogTime, VesselUsageCountersStruct::PortRudderCounter, configValuesType::SDCardLogDelimiter, VesselUsageCountersStruct::StarboardRudderCounter, VesselUsageCountersStruct::TrimTabCounter.
Referenced by SD_Logging_OpenFile.
void Check_GPS_TimeStatus(word LoggingMask)
References CloseThenOpenLogFile, GPS_TimeIs_Valid.
Referenced by SD_Logging.