Wingsail.cpp
HardwareSerial* Serials[][]
Referenced by WingSailServo.
BTStateType BTState
Referenced by WingSailServo.
configValuesType Configuration
WingSailType WingSail
StateValuesStruct StateValues
NavigationDataType NavData
LoiterStruct LoiterData
RC_IN_Type RC_IN
MPU9250 WingSailAngleSensor
WearCounter TrimTabUsage
MissionValuesStruct MissionValues
const uint16_t Deadband
Referenced by WearCounter::TrackServoUsage, WingSailServo.
void wingsail_init(void)
References WingSailType::State, wingsail_update, wsForward.
void wingsail_update(void)
References AutoSetWingSail, RC_IN_Type::Channel, MissionCommand::cmd, StateValuesStruct::CommandState, ctSteerWindCourse, NavigationDataType::Currentloc, GPS_LocationIs_Valid, StateValuesStruct::home_is_set, LoiterStruct::LoiterState, lsNotLoitering, StateValuesStruct::mission_index, MissionValuesStruct::MissionList, NavigationDataType::next_WP_valid, configValuesType::RC_IN_Channel_Sail, SetTrimTabAngle, WingSailType::State, MissionCommand::TrimTabAngle, vcsFollowMission, vcsFullManual, vcsIdle, vcsLoiter, vcsPartialManual, vcsResetMissionIndex, vcsReturnToHome, vcsSetHome, vcsSteerMagneticCourse, vcsSteerWindCourse, WingSailServo, wsForward, wsIdle.
Referenced by wingsail_init, Wingsail_TrackTackChange.
void AutoSetWingSail(WingSailStateType WingSailState)
References WingSailType::Angle, CalcTrimTabAngle, SetTrimTabAngle, WingSailType::TrimTabAngle.
Referenced by wingsail_update.
void SetTrimTabAngle(int TrimTabAngle)
References WingSailType::Servo_microseconds, TrimTabAngle_to_us, WingSailServo.
Referenced by AutoSetWingSail, wingsail_update.
int CalcTrimTabAngle(int WingSailAngle, WingSailStateType WingSailState)
References IdentifyCurrentTack, WingSailType::Tack, configValuesType::TrimTabDefaultAngle, wsForward, wsHeadToWind, wsIdle, wsPortTack, wsReverse, wsStarboardTack.
Referenced by AutoSetWingSail.
int TrimTabAngle_to_us(int TrimTabAngle)
References configValuesType::TrimTabOffset, configValuesType::TrimTabScale.
Referenced by SetTrimTabAngle.
void WingSailServo(int SailIn_us)
References configValuesType::BluetoothPort, BTState, Connected, Deadband, Serials, WearCounter::TrackServoUsage.
Referenced by SetTrimTabAngle, wingsail_update.
void IdentifyCurrentTack(int WingSailAngle)
References WingSailType::Tack, wsHeadToWind, wsPortTack, wsStarboardTack.
Referenced by CalcTrimTabAngle, Wingsail_TrackTackChange.
void Wingsail_TrackTackChange(void)
References WingSailType::Angle, IdentifyCurrentTack, WingSailType::Tack, wingsail_update.