WindAngle_2950.cpp
const byte MPU9250_ID
Referenced by WingSailAngleSensor_Init.
const byte MPU9255_ID
Referenced by WingSailAngleSensor_Init.
MPU9250 WingSailAngleSensor
configValuesType Configuration
HardwareSerial* Serials[][]
Referenced by WingSailAngleSensor_Init.
void WingSailAngleSensor_Init(int CommandPort)
References MPU9250::accelBias, MPU9250::calibrateMPU9250, CommandPort, MPU9250::gyroBias, MPU9250::initAK8963, MPU9250::Initialsed, MPU9250::initMPU9250, Load_IMU_Calibation_Values, MPU9250::magCalibration, MPU9250::MagneticAngleCalibrationMode, MPU9250_ADDRESS, MPU9250_ID, MPU9250::MPU9250SelfTest, MPU9255_ID, MPU9250::readByte, MPU9250::SelfTest, Serials, WHO_AM_I_MPU9250.
void IMU_Mag_Init(void)
References MPU9250::mx, MPU9250::mx_max, MPU9250::mx_min, MPU9250::my, MPU9250::my_max, MPU9250::my_min, MPU9250::mz, MPU9250::mz_max, MPU9250::mz_min, WingSailAngleSensor_Read.
Referenced by CLI_Processor.
void IMU_Mag_Calibrate(void)
References MPU9250::mx, configValuesType::mx_max, MPU9250::mx_max, configValuesType::mx_min, MPU9250::mx_min, MPU9250::my, configValuesType::my_max, MPU9250::my_max, configValuesType::my_min, MPU9250::my_min, MPU9250::mz, configValuesType::mz_max, MPU9250::mz_max, configValuesType::mz_min, MPU9250::mz_min.
Referenced by WingSailAngleSensor_Read.
void WingSailAngleSensor_Read(void)
References MPU9250::accelCount, MPU9250::aRes, MPU9250::ax, MPU9250::ay, MPU9250::az, MPU9250::count, MPU9250::delt_t, MPU9250::getAres, MPU9250::getGres, MPU9250::getMres, MPU9250::gRes, MPU9250::gx, MPU9250::gy, MPU9250::gyroCount, MPU9250::gz, IMU_Mag_Calibrate, INT_STATUS, MPU9250::magbias, MPU9250::magCalibration, MPU9250::magCount, MPU9250::MagneticAngle, MPU9250::MagneticAngleCalibrationMode, MPU9250_ADDRESS, MPU9250::mRes, MPU9250::mx, MPU9250::mx_max, MPU9250::mx_min, MPU9250::my, MPU9250::my_max, MPU9250::my_min, MPU9250::mz, MPU9250::mz_max, MPU9250::mz_min, MPU9250::pitch, MPU9250::readAccelData, MPU9250::readByte, MPU9250::readGyroData, MPU9250::readMagData, MPU9250::readTempData, MPU9250::roll, MPU9250::sum, MPU9250::sumCount, MPU9250::tempCount, MPU9250::temperature, MPU9250::updateTime.
Referenced by IMU_Mag_Init.
void Load_IMU_Calibation_Values(void)
References configValuesType::mx_max, MPU9250::mx_max, configValuesType::mx_min, MPU9250::mx_min, configValuesType::my_max, MPU9250::my_max, configValuesType::my_min, MPU9250::my_min, configValuesType::mz_max, MPU9250::mz_max, configValuesType::mz_min, MPU9250::mz_min.
Referenced by WingSailAngleSensor_Init.