LowPassFilter
float LowPassFilter::last_filtered_value
Referenced by Filter.
float LowPassFilter::FilterConstant
Referenced by Filter, Navigation_Init.
float LowPassFilter::Filter(float Input)
References FilterConstant, last_filtered_value.
Referenced by NavigationUpdate_FastData, NavigationUpdate_MediumData, WearCounter::TrackServoUsage.