I2Cdev
TwoWire* I2Cdev::I2C_Bus
Referenced by I2Cdev, I2Cscan, M24512DFMreadByte, M24512DFMreadBytes, M24512DFMwriteByte, M24512DFMwriteBytes, readByte, readBytes, writeBytes.
I2Cdev::I2Cdev(TwoWire *)
References I2C_Bus.
uint8_t I2Cdev::readByte(uint8_t address, uint8_t subAddress)
References I2C_Bus.
Referenced by EM7180::EM7180_get_WS_params, EM7180::EM7180_set_float_param, EM7180::EM7180_set_gyro_FS, EM7180::EM7180_set_integer_param, EM7180::EM7180_set_mag_acc_FS, EM7180::EM7180_set_WS_params, FetchEventStatus, EM7180::initSensors, EM7180::WS_PassThroughMode, EM7180::WS_Resume.
uint8_t I2Cdev::M24512DFMreadByte(uint8_t device_address, uint8_t data_address1, uint8_t data_address2)
References I2C_Bus.
void I2Cdev::readBytes(uint8_t address, uint8_t subAddress, uint8_t count, uint8_t *dest)
References I2C_Bus.
Referenced by EM7180::Baro_getPress, EM7180::Baro_getTemp, EM7180::getQUAT, EM7180::i2c_getSixRawADC.
void I2Cdev::M24512DFMreadBytes(uint8_t device_address, uint8_t data_address1, uint8_t data_address2, uint8_t count, uint8_t *dest)
References I2C_Bus.
Referenced by EM7180::readAccelCal, EM7180::readSenParams.
void I2Cdev::writeByte(uint8_t devAddr, uint8_t regAddr, uint8_t data)
References writeBytes.
Referenced by EM7180::ACC_Common, EM7180::EM7180_acc_cal_upload, EM7180::EM7180_get_WS_params, EM7180::EM7180_set_float_param, EM7180::EM7180_set_gyro_FS, EM7180::EM7180_set_integer_param, EM7180::EM7180_set_mag_acc_FS, EM7180::EM7180_set_WS_params, EM7180::initSensors, EM7180::WS_PassThroughMode, EM7180::WS_Resume.
void I2Cdev::M24512DFMwriteByte(uint8_t device_address, uint8_t data_address1, uint8_t data_address2, uint8_t data)
References I2C_Bus.
void I2Cdev::writeBytes(uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t *data)
References I2C_Bus.
Referenced by writeByte.
void I2Cdev::M24512DFMwriteBytes(uint8_t device_address, uint8_t data_address1, uint8_t data_address2, uint8_t count, uint8_t *dest)
References I2C_Bus.
Referenced by EM7180::writeAccCal, EM7180::writeSenParams.
void I2Cdev::I2Cscan()
References I2C_Bus.
Referenced by EM7180::initSensors.