Adafruit_GFX
const int16_t Adafruit_GFX::WIDTH
Referenced by Adafruit_GFX, Adafruit_SSD1306::drawFastHLine, Adafruit_SSD1306::drawFastHLineInternal, Adafruit_SSD1306::drawFastVLine, Adafruit_SSD1306::drawFastVLineInternal, Adafruit_SSD1306::drawPixel, GFXcanvas1::drawPixel, GFXcanvas8::drawPixel, GFXcanvas16::drawPixel, GFXcanvas1::fillScreen, GFXcanvas8::fillScreen, GFXcanvas16::fillScreen, setRotation, GFXcanvas8::writeFastHLine.
const int16_t Adafruit_GFX::HEIGHT
Referenced by Adafruit_GFX, Adafruit_SSD1306::drawFastHLine, Adafruit_SSD1306::drawFastHLineInternal, Adafruit_SSD1306::drawFastVLine, Adafruit_SSD1306::drawFastVLineInternal, Adafruit_SSD1306::drawPixel, GFXcanvas1::drawPixel, GFXcanvas8::drawPixel, GFXcanvas16::drawPixel, GFXcanvas1::fillScreen, GFXcanvas8::fillScreen, GFXcanvas16::fillScreen, setRotation, GFXcanvas8::writeFastHLine.
int16_t Adafruit_GFX::_width
Referenced by Adafruit_GFX, charBounds, drawChar, GFXcanvas1::drawPixel, GFXcanvas8::drawPixel, GFXcanvas16::drawPixel, fillScreen, getTextBounds, setRotation, width, write, GFXcanvas8::writeFastHLine.
int16_t Adafruit_GFX::_height
Referenced by Adafruit_GFX, drawChar, GFXcanvas1::drawPixel, GFXcanvas8::drawPixel, GFXcanvas16::drawPixel, fillScreen, getTextBounds, height, setRotation, GFXcanvas8::writeFastHLine.
int16_t Adafruit_GFX::cursor_x
Referenced by Adafruit_GFX, getCursorX, setCursor, write.
int16_t Adafruit_GFX::cursor_y
Referenced by Adafruit_GFX, getCursorY, setCursor, setFont, write.
uint16_t Adafruit_GFX::textcolor
Referenced by Adafruit_GFX, Adafruit_GFX_Button::initButtonUL, setTextColor, write.
uint16_t Adafruit_GFX::textbgcolor
Referenced by Adafruit_GFX, setTextColor, write.
uint8_t Adafruit_GFX::textsize
Referenced by Adafruit_GFX, charBounds, Adafruit_GFX_Button::initButtonUL, setTextSize, write.
uint8_t Adafruit_GFX::rotation
Referenced by Adafruit_GFX, Adafruit_SSD1306::drawFastHLine, Adafruit_SSD1306::drawFastVLine, GFXcanvas1::drawPixel, GFXcanvas8::drawPixel, GFXcanvas16::drawPixel, getRotation, setRotation, GFXcanvas8::writeFastHLine.
boolean Adafruit_GFX::wrap
Referenced by Adafruit_GFX, charBounds, setTextWrap, write.
boolean Adafruit_GFX::_cp437
Referenced by Adafruit_GFX, cp437, drawChar.
GFXfont* Adafruit_GFX::gfxFont
Referenced by Adafruit_GFX, charBounds, drawChar, setFont, write.
Adafruit_GFX::Adafruit_GFX(int16_t w, int16_t h)
References _cp437, _height, _width, cursor_x, cursor_y, gfxFont, HEIGHT, rotation, textbgcolor, textcolor, textsize, WIDTH, wrap.
virtual void Adafruit_GFX::drawPixel(int16_t x, int16_t y, uint16_t color)=0
Referenced by writePixel.
void Adafruit_GFX::startWrite(void)
Referenced by drawBitmap, drawChar, drawCircle, drawFastHLine, drawFastVLine, drawGrayscaleBitmap, drawLine, drawRect, drawRGBBitmap, drawRoundRect, drawXBitmap, fillCircle, fillRect, fillRoundRect, fillTriangle.
void Adafruit_GFX::writePixel(int16_t x, int16_t y, uint16_t color)
References drawPixel.
Referenced by drawBitmap, drawChar, drawCircle, drawCircleHelper, drawGrayscaleBitmap, drawRGBBitmap, drawXBitmap, writeLine.
void Adafruit_GFX::writeFillRect(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
References fillRect.
Referenced by drawChar, fillRoundRect.
void Adafruit_GFX::writeFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color)
References drawFastVLine.
Referenced by drawChar, drawRect, drawRoundRect, fillCircle, fillCircleHelper, fillRect.
void Adafruit_GFX::writeFastHLine(int16_t x, int16_t y, int16_t w, uint16_t color)
References drawFastHLine.
Referenced by drawRect, drawRoundRect, fillTriangle.
void Adafruit_GFX::writeLine(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
References _swap_int16_t, writePixel.
Referenced by drawFastHLine, drawFastVLine, drawLine.
void Adafruit_GFX::endWrite(void)
Referenced by drawBitmap, drawChar, drawCircle, drawFastHLine, drawFastVLine, drawGrayscaleBitmap, drawLine, drawRect, drawRGBBitmap, drawRoundRect, drawXBitmap, fillCircle, fillRect, fillRoundRect, fillTriangle.
void Adafruit_GFX::setRotation(uint8_t r)
References _height, _width, HEIGHT, rotation, WIDTH.
void Adafruit_GFX::invertDisplay(boolean i)
void Adafruit_GFX::drawFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color)
References endWrite, startWrite, writeLine.
Referenced by drawLine, writeFastVLine.
void Adafruit_GFX::drawFastHLine(int16_t x, int16_t y, int16_t w, uint16_t color)
References endWrite, startWrite, writeLine.
Referenced by drawLine, writeFastHLine.
void Adafruit_GFX::fillRect(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
References endWrite, startWrite, writeFastVLine.
Referenced by fillScreen, writeFillRect.
void Adafruit_GFX::fillScreen(uint16_t color)
References _height, _width, fillRect.
void Adafruit_GFX::drawLine(int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
References _swap_int16_t, drawFastHLine, drawFastVLine, endWrite, startWrite, writeLine.
Referenced by drawTriangle.
void Adafruit_GFX::drawRect(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
References endWrite, startWrite, writeFastHLine, writeFastVLine.
void Adafruit_GFX::drawCircle(int16_t x0, int16_t y0, int16_t r, uint16_t color)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawCircleHelper(int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
References writePixel.
Referenced by drawRoundRect.
void Adafruit_GFX::fillCircle(int16_t x0, int16_t y0, int16_t r, uint16_t color)
References endWrite, fillCircleHelper, startWrite, writeFastVLine.
void Adafruit_GFX::fillCircleHelper(int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
References writeFastVLine.
Referenced by fillCircle, fillRoundRect.
void Adafruit_GFX::drawTriangle(int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
References drawLine.
void Adafruit_GFX::fillTriangle(int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
References _swap_int16_t, endWrite, startWrite, writeFastHLine.
void Adafruit_GFX::drawRoundRect(int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
References drawCircleHelper, endWrite, startWrite, writeFastHLine, writeFastVLine.
void Adafruit_GFX::fillRoundRect(int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
References endWrite, fillCircleHelper, startWrite, writeFillRect.
void Adafruit_GFX::drawBitmap(int16_t x, int16_t y, const uint8_t bitmap[], int16_t w, int16_t h, uint16_t color)
References endWrite, pgm_read_byte, startWrite, writePixel.
void Adafruit_GFX::drawBitmap(int16_t x, int16_t y, const uint8_t bitmap[], int16_t w, int16_t h, uint16_t color, uint16_t bg)
References endWrite, pgm_read_byte, startWrite, writePixel.
void Adafruit_GFX::drawBitmap(int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawBitmap(int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawXBitmap(int16_t x, int16_t y, const uint8_t bitmap[], int16_t w, int16_t h, uint16_t color)
References endWrite, pgm_read_byte, startWrite, writePixel.
void Adafruit_GFX::drawGrayscaleBitmap(int16_t x, int16_t y, const uint8_t bitmap[], int16_t w, int16_t h)
References endWrite, pgm_read_byte, startWrite, writePixel.
void Adafruit_GFX::drawGrayscaleBitmap(int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawGrayscaleBitmap(int16_t x, int16_t y, const uint8_t bitmap[], const uint8_t mask[], int16_t w, int16_t h)
References endWrite, pgm_read_byte, startWrite, writePixel.
void Adafruit_GFX::drawGrayscaleBitmap(int16_t x, int16_t y, uint8_t *bitmap, uint8_t *mask, int16_t w, int16_t h)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawRGBBitmap(int16_t x, int16_t y, const uint16_t bitmap[], int16_t w, int16_t h)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawRGBBitmap(int16_t x, int16_t y, uint16_t *bitmap, int16_t w, int16_t h)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawRGBBitmap(int16_t x, int16_t y, const uint16_t bitmap[], const uint8_t mask[], int16_t w, int16_t h)
References endWrite, pgm_read_byte, startWrite, writePixel.
void Adafruit_GFX::drawRGBBitmap(int16_t x, int16_t y, uint16_t *bitmap, uint8_t *mask, int16_t w, int16_t h)
References endWrite, startWrite, writePixel.
void Adafruit_GFX::drawChar(int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
References _cp437, _height, _width, GFXfont::bitmap, GFXglyph::bitmapOffset, endWrite, GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, pgm_read_byte, pgm_read_pointer, startWrite, GFXglyph::width, writeFastVLine, writeFillRect, writePixel, GFXglyph::xOffset, GFXglyph::yOffset.
Referenced by write.
void Adafruit_GFX::setCursor(int16_t x, int16_t y)
References cursor_x, cursor_y.
Referenced by OLED_Logging.
void Adafruit_GFX::setTextColor(uint16_t c)
References textbgcolor, textcolor.
Referenced by OLED_Init.
void Adafruit_GFX::setTextColor(uint16_t c, uint16_t bg)
References textbgcolor, textcolor.
void Adafruit_GFX::setTextSize(uint8_t s)
References textsize.
Referenced by OLED_Init, OLED_Logging.
void Adafruit_GFX::setTextWrap(boolean w)
References wrap.
void Adafruit_GFX::cp437(boolean x=true)
References _cp437.
void Adafruit_GFX::setFont(const GFXfont *f=NULL)
References cursor_y, gfxFont.
void Adafruit_GFX::getTextBounds(char *string, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
References _height, _width, charBounds.
void Adafruit_GFX::getTextBounds(const __FlashStringHelper *s, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
References _height, _width, charBounds, pgm_read_byte.
size_t Adafruit_GFX::write(uint8_t)
References _width, cursor_x, cursor_y, drawChar, GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, GFXfont::last, pgm_read_byte, pgm_read_pointer, textbgcolor, textcolor, textsize, GFXglyph::width, wrap, GFXglyph::xAdvance, GFXglyph::xOffset, GFXfont::yAdvance.
int16_t Adafruit_GFX::height(void) const
References _height.
Referenced by Adafruit_SSD1306::drawPixel.
int16_t Adafruit_GFX::width(void) const
References _width.
Referenced by Adafruit_SSD1306::drawPixel.
uint8_t Adafruit_GFX::getRotation(void) const
References rotation.
Referenced by Adafruit_SSD1306::drawPixel.
int16_t Adafruit_GFX::getCursorX(void) const
References cursor_x.
int16_t Adafruit_GFX::getCursorY(void) const
References cursor_y.
void Adafruit_GFX::charBounds(char c, int16_t *x, int16_t *y, int16_t *minx, int16_t *miny, int16_t *maxx, int16_t *maxy)
References _width, GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, GFXfont::last, pgm_read_byte, pgm_read_pointer, textsize, GFXglyph::width, wrap, GFXglyph::xAdvance, GFXglyph::xOffset, GFXfont::yAdvance, GFXglyph::yOffset.
Referenced by getTextBounds.