Adafruit_SSD1306
int8_t Adafruit_SSD1306::_i2caddr
Referenced by begin, display, ssd1306_command.
int8_t Adafruit_SSD1306::_vccstate
Referenced by begin, dim.
int8_t Adafruit_SSD1306::sid
Referenced by Adafruit_SSD1306, begin, display, fastSPIwrite, ssd1306_command.
int8_t Adafruit_SSD1306::sclk
Referenced by Adafruit_SSD1306, begin, fastSPIwrite.
int8_t Adafruit_SSD1306::dc
Referenced by Adafruit_SSD1306, begin, display, ssd1306_command.
int8_t Adafruit_SSD1306::rst
Referenced by Adafruit_SSD1306, begin.
int8_t Adafruit_SSD1306::cs
Referenced by Adafruit_SSD1306, begin, display, ssd1306_command.
boolean Adafruit_SSD1306::hwSPI
Referenced by Adafruit_SSD1306, begin, fastSPIwrite.
Adafruit_SSD1306::Adafruit_SSD1306(int8_t SID, int8_t SCLK, int8_t DC, int8_t RST, int8_t CS)
References cs, dc, hwSPI, rst, sclk, sid.
Adafruit_SSD1306::Adafruit_SSD1306(int8_t DC, int8_t RST, int8_t CS)
References cs, dc, hwSPI, rst.
Adafruit_SSD1306::Adafruit_SSD1306(int8_t RST=-1)
References cs, dc, rst, sclk, sid.
void Adafruit_SSD1306::begin(uint8_t switchvcc=SSD1306_SWITCHCAPVCC, uint8_t i2caddr=SSD1306_I2C_ADDRESS, bool reset=true)
References _i2caddr, _vccstate, cs, dc, hwSPI, rst, sclk, sid, SSD1306_CHARGEPUMP, ssd1306_command, SSD1306_COMSCANDEC, SSD1306_DEACTIVATE_SCROLL, SSD1306_DISPLAYALLON_RESUME, SSD1306_DISPLAYOFF, SSD1306_DISPLAYON, SSD1306_EXTERNALVCC, SSD1306_LCDHEIGHT, SSD1306_MEMORYMODE, SSD1306_NORMALDISPLAY, SSD1306_SEGREMAP, SSD1306_SETCOMPINS, SSD1306_SETCONTRAST, SSD1306_SETDISPLAYCLOCKDIV, SSD1306_SETDISPLAYOFFSET, SSD1306_SETMULTIPLEX, SSD1306_SETPRECHARGE, SSD1306_SETSTARTLINE, SSD1306_SETVCOMDETECT.
Referenced by OLED_Init.
void Adafruit_SSD1306::ssd1306_command(uint8_t c)
References _i2caddr, cs, dc, fastSPIwrite, sid.
Referenced by begin, dim, display, invertDisplay, OLED_Logging, startscrolldiagleft, startscrolldiagright, startscrollleft, startscrollright, stopscroll.
void Adafruit_SSD1306::clearDisplay(void)
References buffer, SSD1306_LCDHEIGHT, SSD1306_LCDWIDTH.
Referenced by OLED_Init, OLED_Logging.
void Adafruit_SSD1306::invertDisplay(uint8_t i)
References ssd1306_command, SSD1306_INVERTDISPLAY, SSD1306_NORMALDISPLAY.
void Adafruit_SSD1306::display()
References _i2caddr, buffer, cs, dc, fastSPIwrite, sid, SSD1306_COLUMNADDR, ssd1306_command, SSD1306_LCDHEIGHT, SSD1306_LCDWIDTH, SSD1306_PAGEADDR, WIRE_WRITE.
Referenced by OLED_Init, OLED_Logging.
void Adafruit_SSD1306::startscrollright(uint8_t start, uint8_t stop)
References SSD1306_ACTIVATE_SCROLL, ssd1306_command, SSD1306_RIGHT_HORIZONTAL_SCROLL.
void Adafruit_SSD1306::startscrollleft(uint8_t start, uint8_t stop)
References SSD1306_ACTIVATE_SCROLL, ssd1306_command, SSD1306_LEFT_HORIZONTAL_SCROLL.
void Adafruit_SSD1306::startscrolldiagright(uint8_t start, uint8_t stop)
References SSD1306_ACTIVATE_SCROLL, ssd1306_command, SSD1306_LCDHEIGHT, SSD1306_SET_VERTICAL_SCROLL_AREA, SSD1306_VERTICAL_AND_RIGHT_HORIZONTAL_SCROLL.
void Adafruit_SSD1306::startscrolldiagleft(uint8_t start, uint8_t stop)
References SSD1306_ACTIVATE_SCROLL, ssd1306_command, SSD1306_LCDHEIGHT, SSD1306_SET_VERTICAL_SCROLL_AREA, SSD1306_VERTICAL_AND_LEFT_HORIZONTAL_SCROLL.
void Adafruit_SSD1306::stopscroll(void)
References ssd1306_command, SSD1306_DEACTIVATE_SCROLL.
void Adafruit_SSD1306::dim(boolean dim)
References _vccstate, ssd1306_command, SSD1306_EXTERNALVCC, SSD1306_SETCONTRAST.
void Adafruit_SSD1306::drawPixel(int16_t x, int16_t y, uint16_t color)
References BLACK, buffer, Adafruit_GFX::getRotation, Adafruit_GFX::height, Adafruit_GFX::HEIGHT, INVERSE, SSD1306_LCDWIDTH, ssd1306_swap, WHITE, Adafruit_GFX::width, Adafruit_GFX::WIDTH.
void Adafruit_SSD1306::drawFastVLine(int16_t x, int16_t y, int16_t h, uint16_t color)
References drawFastHLineInternal, drawFastVLineInternal, Adafruit_GFX::HEIGHT, Adafruit_GFX::rotation, ssd1306_swap, Adafruit_GFX::WIDTH.
void Adafruit_SSD1306::drawFastHLine(int16_t x, int16_t y, int16_t w, uint16_t color)
References drawFastHLineInternal, drawFastVLineInternal, Adafruit_GFX::HEIGHT, Adafruit_GFX::rotation, ssd1306_swap, Adafruit_GFX::WIDTH.
void Adafruit_SSD1306::fastSPIwrite(uint8_t c)
References hwSPI, sclk, sid.
Referenced by display, ssd1306_command.
void Adafruit_SSD1306::drawFastVLineInternal(int16_t x, int16_t y, int16_t h, uint16_t color) __attribute__((always_inline))
References BLACK, buffer, Adafruit_GFX::HEIGHT, INVERSE, SSD1306_LCDWIDTH, WHITE, Adafruit_GFX::WIDTH.
Referenced by drawFastHLine, drawFastVLine.
void Adafruit_SSD1306::drawFastHLineInternal(int16_t x, int16_t y, int16_t w, uint16_t color) __attribute__((always_inline))
References BLACK, buffer, Adafruit_GFX::HEIGHT, INVERSE, SSD1306_LCDWIDTH, WHITE, Adafruit_GFX::WIDTH.
Referenced by drawFastHLine, drawFastVLine.