EM7180
I2Cdev* EM7180::I2C
Referenced by ACC_Common, Baro_getPress, Baro_getTemp, EM7180, EM7180_acc_cal_upload, EM7180_get_WS_params, EM7180_set_float_param, EM7180_set_gyro_FS, EM7180_set_integer_param, EM7180_set_mag_acc_FS, EM7180_set_WS_params, getQUAT, i2c_getSixRawADC, initSensors, readAccelCal, readSenParams, writeAccCal, writeSenParams, WS_PassThroughMode, WS_Resume.
uint8_t EM7180::SensorNum
Referenced by ACC_Common, ACC_getADC, EM7180, EM7180_acc_cal_upload, EM7180_get_WS_params, EM7180_set_WS_params, getQUAT, initSensors, LIN_ACC_getADC, readAccelCal, readSenParams, writeAccCal, writeSenParams, WS_Resume.
EM7180::EM7180(I2Cdev *, uint8_t)
References I2C, SensorNum.
void EM7180::ACC_getADC()
References acc, ACC_CAL_ORIENTATION, ACC_ORIENTATION, calibratingA, EM7180_ADDRESS, EM7180_AX, i2c_getSixRawADC, rawADC, SensorNum.
Referenced by ACC_Common, FetchSentralData.
void EM7180::LIN_ACC_getADC()
References accLIN, EM7180_ADDRESS, EM7180_GP8, i2c_getSixRawADC, rawADC, SensorNum.
void EM7180::ACC_Common()
References a_acc, acc_calADC, ACC_getADC, ACC_SCALE, global_conf_t::accZero_max, global_conf_t::accZero_min, b_acc, calibratingA, EM7180_ADDRESS, EM7180_AlgorithmControl, I2C, SensorNum, writeAccCal, I2Cdev::writeByte, WS_PassThroughMode, WS_Resume.
Referenced by FetchSentralData.
void EM7180::Mag_getADC()
References EM7180_ADDRESS, EM7180_MX, i2c_getSixRawADC, MAG_ORIENTATION, rawADC.
Referenced by FetchSentralData.
void EM7180::Save_Sentral_WS_params()
References EM7180_get_WS_params, writeSenParams, WS_PassThroughMode, WS_Resume.
Referenced by IMU_Save_Cal.
void EM7180::Gyro_getADC()
References EM7180_ADDRESS, EM7180_GX, GYRO_ORIENTATION, i2c_getSixRawADC, rawADC.
Referenced by FetchSentralData.
void EM7180::getQUAT()
References EM7180_ADDRESS, EM7180_QX, I2C, qt, QT_Timestamp, I2Cdev::readBytes, SensorNum, uint32_reg_to_float.
Referenced by IMU::computeIMU.
int16_t EM7180::Baro_getPress()
References EM7180_ADDRESS, EM7180_Baro, I2C, I2Cdev::readBytes.
Referenced by FetchSentralData.
int16_t EM7180::Baro_getTemp()
References EM7180_ADDRESS, EM7180_Temp, I2C, I2Cdev::readBytes.
Referenced by FetchSentralData.
void EM7180::initSensors()
References ACC_ODR, ACC_SCALE, ACCEL_CAL, Accel_Cal_valid, global_conf_t::accZero_max, global_conf_t::accZero_min, BARO_ODR, EM7180_acc_cal_upload, EM7180_ACC_LPF_BW, EM7180_AccelRate, EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_BARO_LPF_BW, EM7180_BaroRate, EM7180_EnableEvents, EM7180_EventStatus, EM7180_GYRO_LPF_BW, EM7180_GyroRate, EM7180_HostControl, EM7180_MAG_LPF_BW, EM7180_MagRate, EM7180_PassThruControl, EM7180_PassThruStatus, EM7180_QRateDivisor, EM7180_ResetRequest, EM7180_SentralStatus, EM7180_set_float_param, EM7180_set_gyro_FS, EM7180_set_integer_param, EM7180_set_mag_acc_FS, EM7180_set_WS_params, eventStatus, GYRO_ODR, GYRO_SCALE, I2C, I2Cdev::I2Cscan, LIS2MDL_MAG_LPF, LPS22HB_BARO_LPF, LSM6DSM_ACC_DLPF_CFG, LSM6DSM_GYRO_DLPF_CFG, MAG_ODR, MAG_SCALE, QUAT_DIV, readAccelCal, I2Cdev::readByte, readSenParams, SensorNum, SENTRAL_WARM_START, Sentral_WS_valid, I2Cdev::writeByte.
Referenced by IMU_Init.
void EM7180::i2c_getSixRawADC(uint8_t add, uint8_t reg)
References I2C, rawADC, I2Cdev::readBytes.
Referenced by ACC_getADC, Gyro_getADC, LIN_ACC_getADC, Mag_getADC.
float EM7180::uint32_reg_to_float(uint8_t *buf)
Referenced by getQUAT.
void EM7180::float_to_bytes(float param_val, uint8_t *buf)
Referenced by EM7180_set_float_param.
void EM7180::EM7180_set_gyro_FS(uint16_t gyro_fs)
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_LoadParamByte0, EM7180_LoadParamByte1, EM7180_LoadParamByte2, EM7180_LoadParamByte3, EM7180_ParamAcknowledge, EM7180_ParamRequest, I2C, I2Cdev::readByte, I2Cdev::writeByte.
Referenced by initSensors.
void EM7180::EM7180_set_mag_acc_FS(uint16_t mag_fs, uint16_t acc_fs)
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_LoadParamByte0, EM7180_LoadParamByte1, EM7180_LoadParamByte2, EM7180_LoadParamByte3, EM7180_ParamAcknowledge, EM7180_ParamRequest, I2C, I2Cdev::readByte, I2Cdev::writeByte.
Referenced by initSensors.
void EM7180::EM7180_set_integer_param(uint8_t param, uint32_t param_val)
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_LoadParamByte0, EM7180_LoadParamByte1, EM7180_LoadParamByte2, EM7180_LoadParamByte3, EM7180_ParamAcknowledge, EM7180_ParamRequest, I2C, I2Cdev::readByte, I2Cdev::writeByte.
Referenced by initSensors.
void EM7180::EM7180_set_float_param(uint8_t param, float param_val)
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_LoadParamByte0, EM7180_LoadParamByte1, EM7180_LoadParamByte2, EM7180_LoadParamByte3, EM7180_ParamAcknowledge, EM7180_ParamRequest, float_to_bytes, I2C, I2Cdev::readByte, I2Cdev::writeByte.
Referenced by initSensors.
void EM7180::EM7180_acc_cal_upload()
References ACC_DOWN, ACC_EAST, ACC_NORTH, ACCEL_CAL, Accel_Cal_valid, global_conf_t::accZero_max, global_conf_t::accZero_min, EM7180_ADDRESS, EM7180_GP36, EM7180_GP37, EM7180_GP38, EM7180_GP39, EM7180_GP40, EM7180_GP50, EM7180_GP51, EM7180_GP52, EM7180_GP53, EM7180_GP54, EM7180_GP55, EM7180_GP56, I2C, SensorNum, I2Cdev::writeByte.
Referenced by initSensors.
void EM7180::EM7180_set_WS_params()
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_LoadParamByte0, EM7180_LoadParamByte1, EM7180_LoadParamByte2, EM7180_LoadParamByte3, EM7180_ParamAcknowledge, EM7180_ParamRequest, I2C, I2Cdev::readByte, Sentral_WS_params::Sen_param, SensorNum, I2Cdev::writeByte.
Referenced by initSensors.
void EM7180::EM7180_get_WS_params()
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_ParamAcknowledge, EM7180_ParamRequest, EM7180_SavedParamByte0, EM7180_SavedParamByte1, EM7180_SavedParamByte2, EM7180_SavedParamByte3, I2C, I2Cdev::readByte, Sentral_WS_params::Sen_param, SensorNum, I2Cdev::writeByte.
Referenced by Save_Sentral_WS_params.
void EM7180::WS_PassThroughMode()
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_PassThruControl, EM7180_PassThruStatus, I2C, I2Cdev::readByte, I2Cdev::writeByte.
Referenced by ACC_Common, Save_Sentral_WS_params.
void EM7180::WS_Resume()
References EM7180_ADDRESS, EM7180_AlgorithmControl, EM7180_AlgorithmStatus, EM7180_EventStatus, EM7180_PassThruControl, EM7180_PassThruStatus, eventStatus, I2C, I2Cdev::readByte, SensorNum, I2Cdev::writeByte.
Referenced by ACC_Common, Save_Sentral_WS_params.
void EM7180::readSenParams()
References I2C, M24512DFM_DATA_ADDRESS, I2Cdev::M24512DFMreadBytes, Sentral_WS_params::Sen_param, SensorNum, Sentral_WS_valid.
Referenced by initSensors.
void EM7180::writeSenParams()
References I2C, M24512DFM_DATA_ADDRESS, I2Cdev::M24512DFMwriteBytes, Sentral_WS_params::Sen_param, SensorNum, Sentral_WS_valid.
Referenced by Save_Sentral_WS_params.
void EM7180::readAccelCal()
References global_conf_t::accZero_max, global_conf_t::accZero_min, I2C, M24512DFM_DATA_ADDRESS, I2Cdev::M24512DFMreadBytes, SensorNum.
Referenced by initSensors.
void EM7180::writeAccCal()
References global_conf_t::accZero_max, global_conf_t::accZero_min, I2C, M24512DFM_DATA_ADDRESS, I2Cdev::M24512DFMwriteBytes, SensorNum.
Referenced by ACC_Common.