configValues.cpp
configValuesType Configuration
MissionCommand MissionList[MaxMissionCommands][MaxMissionCommands]
MissionValuesStruct MissionValues
StateValuesStruct StateValues
HardwareSerial* Serials[][]
Referenced by Load_ConfigValues.
WearCounter PortRudderUsage
WearCounter StarboardRudderUsage
WearCounter TrimTabUsage
VesselUsageCountersStruct VesselUsageCounters
const int VesselUsageCountersAddress
Referenced by Load_EEPROM_VesselUsage, Save_EEPROM_VesselUsage.
const int sizeof_VesselUsageCounters
const int ConfigurationAddress
Referenced by Load_EEPROM_ConfigValues, Save_EEPROM_ConfigValues.
const int sizeof_Configuration
const int MissionValuesAddress
Referenced by load_EEPROM_Mission, Save_EEPROM_Mission.
const int sizeof_MissionValues
const int StateValuesAddress
Referenced by Load_EEPROM_StateValues, Save_EEPROM_StateValues.
const int sizeof_StateValues
const int TotalEEPROMStorage
void Save_EEPROM_VesselUsage(void)
References WearCounter::Counter, EEPROM_write, VesselUsageCountersStruct::PortRudderCounter, VesselUsageCountersStruct::StarboardRudderCounter, VesselUsageCountersStruct::TrimTabCounter, VesselUsageCountersAddress.
void Load_EEPROM_VesselUsage(void)
References WearCounter::Counter, EEPROM_read, VesselUsageCountersStruct::init_flag, VesselUsageCountersStruct::intervalCounter, VesselUsageCountersStruct::PortRudderCounter, VesselUsageCountersStruct::SpareCounter1, VesselUsageCountersStruct::SpareCounter2, VesselUsageCountersStruct::SpareCounter3, VesselUsageCountersStruct::StarboardRudderCounter, VesselUsageCountersStruct::TrimTabCounter, VesselUsageCountersAddress.
Referenced by init_wearTracking.
void Save_EEPROM_ConfigValues(void)
References ConfigurationAddress, configValuesType::EEPROM_Storage_Version, EEPROM_Storage_Version_Const, EEPROM_write.
Referenced by CLI_Processor.
void Load_EEPROM_ConfigValues(void)
References ConfigurationAddress, EEPROM_read.
Referenced by Load_ConfigValues.
void load_EEPROM_Mission(void)
References EEPROM_read, MaxMissionCommands, MissionValuesStruct::mission_size, MissionValuesAddress.
Referenced by Load_ConfigValues.
void Save_EEPROM_Mission(void)
References EEPROM_write, MissionValuesAddress.
Referenced by CLI_Processor.
void Load_EEPROM_StateValues(void)
References StateValuesStruct::CommandState, EEPROM_read, StateValuesStruct::mission_index, MissionValuesStruct::mission_size, StateValuesStruct::StartingMission, StateValuesAddress, vcsFullManual.
Referenced by Load_ConfigValues.
void Save_EEPROM_StateValues(void)
References EEPROM_write, StateValuesAddress.
Referenced by CLI_Processor, MissionUpdate.
bool EEPROM_Storage_Version_Valid(void)
References configValuesType::EEPROM_Storage_Version, EEPROM_Storage_Version_Const.
Referenced by Load_ConfigValues.
void Load_Config_default_values(void)
References configValuesType::BluetoothPort, configValuesType::BTPortBaudRate, configValuesType::CommandPort, configValuesType::CommandPortBaudRate, configValuesType::CompassOffsetAngle, configValuesType::CTE_CorrectionGain, configValuesType::DisplayScreenView, configValuesType::DualRudder, configValuesType::FailsafeCommandState, configValuesType::LoiterRadius, configValuesType::MagnetVariation, configValuesType::MaxFileSize, configValuesType::MaximumTimePastFavouredTack, configValuesType::MinimumAngleDownWind, configValuesType::MinimumAngleUpWind, configValuesType::MinimumWindChangeTime, mtGybe, configValuesType::mx_max, configValuesType::mx_min, configValuesType::my_max, configValuesType::my_min, configValuesType::mz_max, configValuesType::mz_min, configValuesType::pidCentre, configValuesType::pidDirection, configValuesType::pidKd, configValuesType::pidKi, configValuesType::pidKp, configValuesType::pidOutputmax, configValuesType::pidOutputmin, configValuesType::RC_FailSafe_Ch0, configValuesType::RC_FailSafe_Ch1, configValuesType::RC_FailSafe_Ch2, configValuesType::RC_FailSafe_Ch3, configValuesType::RC_FailSafe_Time, configValuesType::RC_IN_Channel_Command, configValuesType::RC_IN_Channel_Motor, configValuesType::RC_IN_Channel_Sail, configValuesType::RC_IN_Channel_Steering, configValuesType::RC_IN_Command_Threhold0, configValuesType::RC_IN_Command_Threhold1, configValuesType::RC_IN_Command_Threhold2, configValuesType::RC_IN_Command_Threhold3, configValuesType::RC_IN_Command_Threhold4, configValuesType::RC_IN_Command_Threhold9, REVERSE, configValuesType::SailableAngleMargin, configValuesType::SatCommsPort, configValuesType::SatCommsPortBaudRate, configValuesType::SaveStateValues, configValuesType::SDCardLogDelimiter, configValuesType::SDCardLoggingMask, configValuesType::Servo_Channel_Motor, configValuesType::Servo_Channel_Sail, configValuesType::Servo_Channel_Steering, configValuesType::Servo_Channel_Steering_Stbd, configValuesType::TackingMethod, configValuesType::TargetHeadingFilterConstant, configValuesType::TelemetryLoggingMask, configValuesType::timezone_offset, configValuesType::TrimTabDefaultAngle, configValuesType::TrimTabOffset, configValuesType::TrimTabScale, configValuesType::TWD_Offset, configValuesType::UseMotor, vcsFollowMission, configValuesType::WindAngleCalibrationOffset, configValuesType::WPCourseHoldRadius.
Referenced by Load_ConfigValues.
void Load_ConfigValues(int CommandPort, bool SerialLog)
References CLI_Processor, CommandPort, configValuesType::CommandPort, configValuesType::EEPROM_Storage_Version, EEPROM_Storage_Version_Const, EEPROM_Storage_Version_Valid, Load_Config_default_values, Load_EEPROM_ConfigValues, load_EEPROM_Mission, Load_EEPROM_StateValues, MissionValuesStruct::mission_size, configValuesType::SaveStateValues, Serials.