TinyGPSTime
friend class TinyGPSPlus
bool TinyGPSTime::valid
Referenced by age, commit, isValid.
bool TinyGPSTime::updated
Referenced by centisecond, commit, hour, isUpdated, minute, second, value.
uint32_t TinyGPSTime::time
Referenced by centisecond, commit, hour, minute, second, value.
uint32_t TinyGPSTime::newTime
Referenced by commit, setTime.
uint32_t TinyGPSTime::lastCommitTime
Referenced by age, commit.
bool TinyGPSTime::isValid() const
References valid.
bool TinyGPSTime::isUpdated() const
References updated.
uint32_t TinyGPSTime::age() const
References lastCommitTime, valid.
uint32_t TinyGPSTime::value()
References time, updated.
uint8_t TinyGPSTime::hour()
References time, updated.
Referenced by GPS_Read, GPS_Read_Time.
uint8_t TinyGPSTime::minute()
References time, updated.
Referenced by GPS_Read, GPS_Read_Time.
uint8_t TinyGPSTime::second()
References time, updated.
Referenced by GPS_Read, GPS_Read_Time.
uint8_t TinyGPSTime::centisecond()
References time, updated.
TinyGPSTime::TinyGPSTime()
void TinyGPSTime::commit()
References lastCommitTime, newTime, time, updated, valid.
Referenced by TinyGPSPlus::endOfTermHandler.
void TinyGPSTime::setTime(const char *term)
References newTime, TinyGPSPlus::parseDecimal.
Referenced by TinyGPSPlus::endOfTermHandler.